-------------------------
-- English Localization String resources
-- Huami Co, ltd. (2014)
-- Herbert dai
-- 20140731
-------------------------
localization_English_table = {
    calories_table={
        {str="≈ Cucumber (100g)",   calories=14},
        {str="≈ Chicken broth (100g)",  calories=15},
        {str="≈ Cabbage (100g)",    calories=16},
        {str="≈ Pickled tomatoes (100g)",   calories=19},
        {str="≈ Mushrooms (100g)",  calories=20},
        {str="≈ Radishes (100g)",   calories=21},
        {str="≈ Eggplant (100g)",   calories=24},
        {str="≈ Pumpkin (100g)",    calories=25},
        {str="≈ Sauerkraut (100g)", calories=25},
        {str="≈ Mushroom soup (100g)",  calories=26},
        {str="≈ Broccoli (100g)",   calories=27},
        {str="≈ Vegetable soup (100g)", calories=28},
        {str="≈ Strawberries (100g)",   calories=30},
        {str="≈ Borsch (100g)", calories=36},
        {str="≈ Miso soup (100g)",  calories=36},
        {str="≈ Beetroot (100g)",   calories=36},
        {str="≈ Apple (100g)",  calories=37},
        {str="≈ Orange (100g)", calories=38},
        {str="≈ Potato soup (100g)",    calories=39},
        {str="≈ Watermelon (100g)", calories=39},
        {str="≈ Sorrel soup (100g)",    calories=40},
        {str="≈ Buttermilk 1% (100g)",  calories=40},
        {str="≈ Coca-Cola (100g)",  calories=42},
        {str="≈ 1.5% Milk (100g)",  calories=45},
        {str="≈ Red Bull (100g)",   calories=45},
        {str="≈ Chowder (100g)",    calories=46},
        {str="≈ Peach (100g)",  calories=46},
        {str="≈ Hochland cheese (25g)", calories=48},
        {str="≈ Cherry (100g)", calories=52},
        {str="≈ Orange juice (100g)",   calories=54},
        {str="≈ 3.2% milk (100g)",  calories=58},
        {str="≈ Ratatouille (100g)",    calories=60},
        {str="≈ Mashed potatoes (100g)",    calories=65},
        {str="≈ Pea soup (100g)",   calories=66},
        {str="≈ Mango (100g)",  calories=67},
        {str="≈ Lentil Soup (100g)",    calories=68},
        {str="≈ Strawberry jelly (100g)",   calories=69},
        {str="≈ Yogurt 1.5% (100g)",    calories=70},
        {str="≈ Crab sticks (100g)",    calories=73},
        {str="≈ Squid (100g)",  calories=75},
        {str="≈ Champagne (100g)",  calories=76},
        {str="≈ Wine 13% (100g)",   calories=78},
        {str="≈ Cabbage goulash (100g)",    calories=81},
        {str="≈ Boiled potatoes (100g)",    calories=82},
        {str="≈ Absinthe 60% ​​(100g)", calories=83},
        {str="≈ Milk mashed potatoes (100g)",   calories=85},
        {str="≈ Boiled egg (55g)",  calories=88},
        {str="≈ Banana (100g)", calories=89},
        {str="≈ Tomato beans (100g)",   calories=92},
        {str="≈ Ketchup (100g)",    calories=93},
        {str="≈ Rice with vegetables (100g)",   calories=94},
        {str="≈ Grain toast (1 slice)", calories=95},
        {str="≈ Tuna (100g)",   calories=96},
        {str="≈ Boiled walleye (100g)", calories=97},
        {str="≈ Vegetable stew (100g)", calories=99},
        {str="≈ Boiled carp (100g)",    calories=102},
        {str="≈ Fruit salad (100g)",    calories=103},
        {str="≈ Turkey fillet (100g)",  calories=104},
        {str="≈ Pork sturgeon (100g)",  calories=105},
        {str="≈ Rice (100g)",   calories=113},
        {str="≈ Zeppelins (100g)",  calories=117},
        {str="≈ Scrambled egg", calories=119},
        {str="≈ Squash paste (100g)",   calories=122},
        {str="≈ Japanese mayonnaise (100g)",    calories=134},
        {str="≈ Marshmallow (1pc)", calories=135},
        {str="≈ Cottage cheese (100g)", calories=136},
        {str="≈ Avocado roll",  calories=140},
        {str="≈ Cappuccino (100g)", calories=140},
        {str="≈ Lobio (100g)",  calories=141},
        {str="≈ Beef tongue (100g)",    calories=146},
        {str="≈ Beef goulash (100g)",   calories=148},
        {str="≈ Boiled chicken fillet (100g)",  calories=153},
        {str="≈ Fried potato (100g)",   calories=154},
        {str="≈ Pizza Margarita (100g)",    calories=157},
        {str="≈ Meatballs (100g)",  calories=159},
        {str="≈ Buckwheat (100g)",  calories=160},
        {str="≈ Rye bread (100g)",  calories=165},
        {str="≈ Roast turkey (100g)",   calories=165},
        {str="≈ Smoked chicken (100g)", calories=184},
        {str="≈ The cue pork (100g)",   calories=195},
        {str="≈ Sausages (100g)",   calories=198},
        {str="≈ Salmon (201g)", calories=201},
        {str="≈ Sour cream 20% (100g)", calories=204},
        {str="≈ Cream (100g)",  calories=206},
        {str="≈ Pasta Bolognese (100g)",    calories=208},
        {str="≈ Black bread (100g)",    calories=214},
        {str="≈ Candied fruits (100g)", calories=216},
        {str="≈ Salted herring (100g)", calories=217},
        {str="≈ Mushroom julienne (100g)",  calories=219},
        {str="≈ Caesar salad (100g)",   calories=221},
        {str="≈ Omelette (100g)",   calories=222},
        {str="≈ Light beer (0.5L)", calories=225},
        {str="≈ Oat bread (100g)",  calories=226},
        {str="≈ Lamb stew (100g)",  calories=226},
        {str="≈ Sundae (100g)", calories=227},
        {str="≈ McD Hamburger", calories=229},
        {str="≈ Roast pork (100g)", calories=233},
        {str="≈ White bread (100g)",    calories=235},
        {str="≈ Pita bread (100g)", calories=236},
        {str="≈ Vodka 40% (100g)",  calories=237},
        {str="≈ Basturma (100g)",   calories=240},
        {str="≈ Hamon (100g)",  calories=241},
        {str="≈ Ravioli (100g)",    calories=245},
        {str="≈ Red caviar (100g)", calories=249},
        {str="≈ Shawarma (100g)",   calories=250},
        {str="≈ Chicken sausages (100g)",   calories=259},
        {str="≈ Cutlets (100g)",    calories=260},
        {str="≈ Raisins (100g)",    calories=262},
        {str="≈ McD Cheeseburger",  calories=264},
        {str="≈ Milk sausages (100g)",  calories=270},
        {str="≈ Ham (100g)",    calories=270},
        {str="≈ Capelin smoked (100g)", calories=270},
        {str="≈ McD McNuggets (100g)",  calories=272},
        {str="≈ Dumplings (100g)",  calories=275},
        {str="≈ Grilled salmon (100g)", calories=283},
        {str="≈ Black Caviar (100g)",   calories=289},
        {str="≈ Mayonnaise (100g)", calories=299},
        {str="≈ Honey (100g)",  calories=302},
        {str="≈ McD Fries (100 g)", calories=303},
        {str="≈ Dates (100g)",  calories=306},
        {str="≈ Apple pancakes (100g)", calories=306},
        {str="≈ Stuffed cabbage (100g)",    calories=311},
        {str="≈ Pancakes (100g)",   calories=322},
        {str="≈ Omelet with cheese (100g)", calories=324},
        {str="≈ Liver sausages (100g)", calories=326},
        {str="≈ Donuts (100g)", calories=329},
        {str="≈ Cheesecake (100g)", calories=331},
        {str="≈ Pancakes with butter (100g)",   calories=332},
        {str="≈ Kebab (100g)",  calories=339},
        {str="≈ Spaghetti (100g)",  calories=344},
        {str="≈ Muffin (100g)", calories=345},
        {str="≈ Gingerbread (100g)",    calories=350},
        {str="≈ Beef stroganoff (100g)",    calories=355},
        {str="≈ Cornflakes (100g)", calories=363},
        {str="≈ Pasta (100g)",  calories=371},
        {str="≈ Steak (100g)",  calories=384},
        {str="≈ Crackers (100g)",   calories=386},
        {str="≈ Sugar (100g)",  calories=398},
        {str="≈ Oatmeal cookies (100g)",    calories=440},
        {str="≈ Schnitzel (100g)",  calories=456},
        {str="≈ Lasagne (100g)",    calories=460},
        {str="≈ Foie Gras (100g)",  calories=462},
        {str="≈ Honey cake (100g)", calories=478},
        {str="≈ Popcorn (100g)",    calories=480},
        {str="≈ Twix",  calories=483},
        {str="≈ Snickers",  calories=497},
        {str="≈ Bacon (100g)",  calories=500},
        {str="≈ McD Big Mac",   calories=510},
        {str="≈ Lays Max chips (100g)", calories=510},
        {str="≈ KitKat",    calories=524},
        {str="≈ Tiramisu (100g)",   calories=540},
        {str="≈ Pringles (100g)",   calories=540},
        {str="≈ Chocolate (100g)",  calories=546},
        {str="≈ Napoleon cake (100g)",  calories=552},
        {str="≈ Salami (100g)", calories=568},
        {str="≈ Roast goose (100g)",    calories=620},
        {str="≈ Fried dumplings (100g)",    calories=764},
        {str="≈ McD Big Tasty", calories=850},
    },

    ok='OK',

    hour='hrs',
    minute='min',
    month='month',
    day='day',
    step="steps",
    km='km',
    mile='miles',
    minute_format='%dmin',
    hour_minute_format='%dh %dm',
    hour_format='%dhrs',

    welcome_use="Welcome",
    last_week_walked_format='You walked %d steps last week.',
    last_week_walked_info_format='Walked %dkm, burned %dcal.',
    last_month_walked_format='You walked %d steps last month.',
    last_month_walked_info_format='Walked %dkm, burned %dcal.',

    get_over_format=", about %d grams of fat.",
    click_to_get_help="Learn more about Mi Band",
    take_a_walk="Take a walk with your band",
    take_a_walk_info="Your band keeps track of every step you take throughout the day.",
    unlock_hint="Open sesame!",
    unlock_hint_info="Use your band to unlock your device automatically.",
    no_data_hint_0="The US National Sleep Foundation recommends between 7-9 hours of sleep per night.",
    no_data_hint_1="Repetition is the father of success.",
    no_data_hint_2="Strive for progress, not perfection.",
    no_data_hint_3="No matter how slow you go, you're still lapping everybody on the couch.",
    not_binded_hint="No bands have been added to this account.",
    new_record_info="You set a new record!",
    new_record_format="%d steps, %s %d",
    today_goal_reached="You reached your goal today!",
    week_continue_reach_goal="You",
    unlock_password_hint="Set screen lock to keep phone secure.",
    unlock_password_hint_info="Mi Band gives the best screen unlocker.",

    challenge_format="You've hit your goal for %d days in a row!",
    personal_best_format="Your longest streak is %d days!",
    continue_with_skips_title="You didn't hit your goal yesterday. Let's call it a Lazy Day ;)",
    continue_with_skips_title_today="You didn't hit your goal today. Let's call it a Lazy Day ;)",
    personal_best_with_skips_format="You have %d Lazy Days left ;)",
    continue_used_n_skips_format="You've hit your goal for %d days in a row! You still have %d Lazy Days",
    continue_used_0_skips_format="You've hit your goal for %d days in a row! You have no Lazy Days left.",
    personal_best_on_skip_day_title="%d day streak! You've earned a Lazy Day!",
    personal_best_on_skip_day_info="After every 7-day streak you earn a Lazy Day. You can use Lazy Days to cover days when you don't hit your goal.",
    manual_lazy_title="You didn't hit your goal today.",
    manual_lazy_subtitle="Your streak will continue if you mark today as a Lazy Day.",
    manual_lazy_title_used="Today is a Lazy Day.",
    manual_lazy_subtitle_used="You can earn more Lazy Days by breaking personal records.",
    manual_fail_ytd_title = "You ended your streak yesterday.",
    manual_fail_ytd_subtitle = "Streak was %d long.",

    active_time_format_0="%dm",
    active_time_format_1="%dh",
    active_time_format_2="%dh %dm",
    activie_run_format_0="Ran %s. Great job!",
    activie_run_format_1="Ran %s. You're doing great!",
    activie_run_format_2="Ran %s.",
    activie_run_consumed="Burned %dcal. %s",

    get_distance_format="about %dm.",
    get_distance_format_british="%d inches",
    activity_walk_format="%s Walked %d steps, %s",
    activity_walk_consumed_format="Burned %dcal%s.",
    activity_rope_skipping_format="%s jumped rope %d times",
    activity_situp_format="%s %d sit-ups",
    activity_consumed_format="Burned %dcal %s",
    activity_activity_format="%s Worked out for %s, %s",
    activity_activity_format_run="%s Worked out for %s, ran %s",
    last_night_sleeped_good_format="You slept for %s last night.",
    last_night_sleeped_normal_format="You slept for %s last night.",
    deep_sleep_format="Deep sleep lasted %s.",

    battery_low_info="Charge your band",
    battery_very_low_info="Your band's battery is running low.",

    cannot_find_bracelet="Can't find your band.",
    cannot_find_bracelet_info="Make sure your band's battery is charged.",
    challenge_to_get="%s days from setting a new record!",
    record_reach_max="You've tied your existing record!",
    new_record_born="You set a new record.",

    --=================== Game =====================
    game_register="国庆七天日行万步, 赢取小米手机4",
    game_not_register_info="分享微博赢取微博大奖",
    game_register_info="已成功报名, 倒计时%s天",
    game_playing="国庆七天日行万步, 第%s天挑战中",
    game_playing_done="国庆七天日行万步, 第%s天达成",
    game_playing_lastday="最后一天即将完成日行万步挑战, 加油",
    game_playing_lastday_done="恭喜, 国庆七天日行万步挑战成功",
    game_playing_bonus_info="中将结果将在%s月%s日揭晓",
    click_to_show_result="点击查看活动进展",
    game_fail_title_ytd="很遗憾, 昨天未达成10000步",
    game_fail_title="很遗憾, %s月%s日未达成10000步",
    game_failed_title="国庆七天日行万步",
    game_fail_info="继续关注活动, 分享微博赢取微博大奖",

    game_bonus_hit="恭喜你成为“国庆七天日行万步”获奖者",
    game_bonus_hit_info="点击查看中奖结果",
    game_bonus_miss="国庆七天日行万步, 中奖结果已经揭晓",
    game_bonus_miss_info="快去看看哪些人中奖了吧",
    game_bonus_open="中奖结果将在%s月%s日揭晓, 敬请关注",
    game_bonus_open_tomorrow="中奖结果将在明天揭晓, 敬请关注",
    game_bonus_open_today="中奖结果将在今天揭晓, 敬请关注",

    share_to_content_for_event="“国庆七天日行万步得小米手机4”活动火热报名中，没有手环? 转发此微博即有机会赢取手环F码，点击链接查看活动详情。",
    game_share_to_registered="我报名参加了“日行万步得小米手机4”的活动，你愿意站在一旁默默祝福我还是一起来参加呢？离活动开始只剩%s天了, 快来报名吧",
    game_share_to_finished="今天10000步目标顺利完成",
    game_share_to_not_finished="向着10000步前进",
    game_share_to_failed="没想到呀，我居然挑战失败了",
    game_share_to_success="挑战成功！一共走了%s步",
    game_share_to_hit_bonus="一个不小心中奖了，快来围观给我点赞吧",
    game_share_to_not_hit_bonus="没有抽中，就当是给下次中奖攒人品了",
    less_than_one="小于1",

    ---====== Weather tips ===============
    weather_tips_title_0 = "Heavy pollution, try to stay indoors",
    weather_tips_title_1 = "Heavy pollution, try to stay indoors",
    weather_tips_info = "Sit-ups or jumping rope are great indoor exercises!",
    today_goal_reached_click_info="Click to see the results.",

    ---------------Weight scale -------------------
    welcome_use_weight_scale = "Welcome use weight scale",
    welcome_use_weight_scale_not_bind = "Click to bind weight scale",
    welcome_use_mi_health="Welcome use Mi Fit",

    select_devices="Select devices to bind now",
    daily_steps_not_comlete = "Still need %s steps to go!"
}

 localization_Slovak_table = {
    calories_table={
	{str="≈ Uhorka (100g)", calories=14}, 
	{str="≈ Kurací vývar (100g)", calories=15}, 
	{str="≈ Kapusta (100g)", calories=16}, 
	{str="≈ Nakladané paradajky (100g)", calories=19}, 
	{str="≈ Huby (100g)", calories=20}, 
	{str="≈ Reďkovky (100g)", calories=21}, 
	{str="≈ Baklažán (100g)", calories=24}, 
	{str="≈ Tekvica (100g)", calories=25}, 
	{str="≈ Kyslá kapusta (100g)", calories=25}, 
	{str="≈ Hubová polievka (100g)", calories=26}, 
	{str="≈ Brokolica (100g)", calories=27}, 
	{str="≈ Zeleninová polievka (100g)", calories=28}, 
	{str="≈ Jahody (100g)", calories=30}, 
	{str="≈ Boršč (100g)", calories=36}, 
	{str="≈ Miso polievka (100g)", calories=36}, 
	{str="≈ Červenej repy (100g)", calories=36}, 
	{str="≈ Jablká (100g)", calories=37}, 
	{str="≈ Pomaranč (100g)", calories=38}, 
	{str="≈ Zemiaková polievka (100g)", calories=39}, 
	{str="≈ Melón (100g)", calories=39}, 
	{str="≈ šťavel polievka (100g)", calories=40}, 
	{str="≈ Cmar 1% (100g)", calories=40}, 
	{str="≈ Coca-Cola (100g)", calories=42}, 
	{str="≈ 1,5% mlieko (100g)", calories=45}, 
	{str="≈ Red Bull (100g)", calories=45}, 
	{str="≈ Polievka (100g)", calories=46}, 
	{str="≈ Broskýňa (100g)", calories=46}, 
	{str="≈ Hochland syr (25g)", calories=48}, 
	{str="≈ Čerešne (100g)", calories=52}, 
	{str="≈ Pomarančový džús (100g)", calories=54}, 
	{str="≈ 3,2% mlieko (100g)", calories=58}, 
	{str="≈ Ratatouille (100g)", calories=60}, 
	{str="≈ Zemiaková kaša (100g)", calories=65}, 
	{str="≈ Hrachová polievka (100g)", calories=66}, 
	{str="≈ Mango (100g)", calories=67}, 
	{str="≈ Šošovicová polievka (100g)", calories=68}, 
	{str="≈ Jahodové želé (100g)", calories=69}, 
	{str="≈ Jogurt 1,5% (100g)", calories=70}, 
	{str="≈ Krabie tyčinky (100g)", calories=73}, 
	{str="≈ Squid (100g)", calories=75}, 
	{str="≈ Champagne (100g)", calories=76}, 
	{str="≈ Víno 13% (100g)", calories=78}, 
	{str="≈ Kapustový guláš (100g)", calories=81}, 
	{str="≈ Varené zemiaky (100g)", calories=82}, 
	{str="≈ Absinthe 60% (100g)", calories=83}, 
	{str="≈ Zemiaková kaša s mliekom (100g)", calories=85}, 
	{str="≈ Varené vajcia (55g)", calories=88}, 
	{str="≈ Banán (100g)", calories=89}, 
	{str="≈ Paradajková fazuľa (100g)", calories=92}, 
	{str="≈ Kečup (100g)", calories=93}, 
	{str="≈ Ryža so zeleninou (100g)", calories=94}, 
	{str="≈ Toast (1 plátok)", calories=95}, 
	{str="≈ Tuniak (100g)", calories=96}, 
	{str="≈ Varené walleye (100g)", calories=97}, 
	{str="≈ Zeleninový guláš (100g)", calories=99}, 
	{str="≈ Varený kapor (100g)", calories=102}, 
	{str="≈ Ovocný šalát (100g)", calories=103}, 
	{str="≈ Filet morky (100g)", calories=104}, 
	{str="≈ Údený jeseter (100g)", calories=105}, 
	{str="≈ Ryža (100g)", calories=113}, 
	{str="≈ Zeppelins (100g)", calories=117}, 
	{str="≈ Miešané vajcia", calories=119}, 
	{str="≈ Kaviár z kabačku (100g)", calories=122}, 
	{str="≈ Japonská majonéza (100g)", calories=134}, 
	{str="≈ Marshmallow (1ks)", calories=135},
	{str="≈ Cottage syr (100g)", calories=136}, 
	{str="≈ Avocado", calories=140}, 
	{str="≈ Cappuccino (100g)", calories=140}, 
	{str="≈ Lobi (100g)", calories=141}, 
	{str="≈ Hovädzí jazyk (100g)", calories=146}, 
	{str="≈ Hovädzí guláš (100g)", calories=148}, 
	{str="≈ Varené kuracie rezeň (100g)", calories=153}, 
	{str="≈ Vyprážané zemiakové (100g)", calories=154}, 
	{str="≈ Pizza Margarita (100g)", calories=157}, 
	{str="≈ Fašírky (100g)", calories=159}, 
	{str="≈ Pohánka (100g)", calories=160}, 
	{str="≈ Ražný chlieb (100g)", calories=165}, 
	{str="≈ Pečený moriak (100g)", calories=165}, 
	{str="≈ Údené kuracie (100g)", calories=184}, 
	{str="≈ Bravčové mäso (100g)", calories=195}, 
	{str="≈ Klobásy (100g)", calories=198},
	{str="≈ Lososa (200g)", calories=201}, 
	{str="≈ Smotana 20% (100g)", calories=204}, 
	{str="≈ Krém (100g)", calories=206}, 
	{str="≈ Pasta Bolognese (100g)", calories=208}, 
	{str="≈ Čierny chlieb (100g)", calories=214}, 
	{str="≈ Kandizované ovocie (100g)", calories=216}, 
	{str="≈ Slanečka (100g)", calories=217}, 
	{str="≈ Mushroom julienne (100g)", calories=219}, 
	{str="≈ Caesar šalát (100g)", calories=221}, 
	{str="≈ Omeleta (100g)", calories=222}, 
	{str="≈ Svetlé pivo (0,5l)", calories=225}, 
	{str="≈ Ovsená chlieb (100g)", calories=226}, 
	{str="≈ Dusené jahňacie (100g)", calories=226}, 
	{str="≈ Sundae (100g)", calories=227}, 
	{str="≈ McD Hamburger", calories=229}, 
	{str="≈ Pečené bravčové (100g)", calories=233}, 
	{str="≈ Biely chlieb (100g)", calories=235}, 
	{str="≈ Pita chlieb (100g)", calories=236}, 
	{str="≈ Vodka 40% (100g)", calories=237}, 
	{str="≈ Basturma (100g)", calories=240}, 
	{str="≈ Šunka talianska (100g)", calories=241}, 
	{str="≈ Ravioli (100g)", calories=245}, 
	{str="≈ Červený kaviár (100g)", calories=249}, 
	{str="≈ Shawarma (100g)", calories=250}, 
	{str="≈ Kuracie párky (100g)", calories=259}, 
	{str="≈ Fašírky (100g)", calories=260}, 
	{str="≈ Hrozienka (100g)", calories=262}, 
	{str="≈ McD Cheeseburger", calories=264}, 
	{str="≈ Klobása (100g)", calories=270}, 
	{str="≈ Šunka (100g)", calories=270}, 
	{str="≈ Huňáčik údené (100g)", calories=270}, 
	{str="≈ McD McNuggets (100g)", calories=272}, 
	{str="≈ Knedľa (100g)", calories=275}, 
	{str="≈ Grilovaný losos (100g)", calories=283}, 
	{str="≈ Čierny kaviár (100g)", calories=289}, 
	{str="≈ Majonéza (100g)", calories=299}, 
	{str="≈ Medu (100g)", calories=302}, 
	{str="≈ McD hranolky (100g)", calories=303}, 
	{str="≈ Termíny (100g)", calories=306}, 
	{str="≈ Jablkové palacinky (100g)", calories=306}, 
	{str="≈ Plnená kapusta (100g)", calories=311}, 
	{str="≈ Palacinky (100g)", calories=322}, 
	{str="≈ Omeleta so syrom (100g)", calories=324}, 
	{str="≈ Pečeňová saláma (100g)", calories=326}, 
	{str="≈ Šišky (100g)", calories=329}, 
	{str="≈ Cheesecake (100g)", calories=331}, 
	{str="≈ Lievance (100g)", calories=332}, 
	{str="≈ Kebab (100g)", calories=339}, 
	{str="≈ Špagety (100g)", calories=344}, 
	{str="≈ Muffin (100g)", calories=345}, 
	{str="≈ Perník (100g)", calories=350}, 
	{str="≈ Hovädzí Stroganov (100g)", calories=355}, 
	{str="≈ Cornflakes (100g)", calories=363}, 
	{str="≈ Cestoviny (100g)", calories=371}, 
	{str="≈ Steak (100g)", calories=384}, 
	{str="≈ Sucháre (100g)", calories=386}, 
	{str="≈ Cukor (100g)", calories=398}, 
	{str="≈ Ovsené sušienky (100g)", calories=440}, 
	{str="≈ Rezeň (100g)", calories=456}, 
	{str="≈ Lasagne (100g)", calories=460}, 
	{str="≈ Foie gras (100g)", calories=462}, 
	{str="≈ Medovník (100g)", calories=478}, 
	{str="≈ Pop-corn (100g)", calories=480}, 
	{str="≈ Twix", calories=483}, 
	{str="≈ Snickers", calories=497}, 
	{str="≈ Slanina (100g)", calories=500}, 
	{str="≈ McD Big Mac", calories=510}, 
	{str="≈ Lays Max čipsy (100g)", calories=510}, 
	{str="≈ KitKat", calories=524}, 
	{str="≈ Tiramisu (100g)", calories=540}, 
	{str="≈ Pringles (100g)", calories=540}, 
	{str="≈ čokoláda (100g)", calories=546}, 
	{str="≈ Napoleon torta (100g)", calories=552}, 
	{str="≈ Saláma (100g)", calories=568}, 
	{str="≈ Pečená hus (100g)", calories=620}, 
	{str="≈ Vyprážané knedle (100g)", calories=764}, 
	{str="≈ McD Big Tasty", calories=850}, 
    },

    ok='OK',

    hour='hod',
    minute='min',
    month='mesiac',
    day='deň',
    step="krok",
    km='km',
    minute_format='%dmin',
    hour_minute_format='%dh %dm',
    hour_format='%dh',

    welcome_use="Vitajte...",
    last_week_walked_format='Minulý týždeň ste prešli %d krokov',
    last_week_walked_info_format='Prešli ste %d km a spálili %d kcal',
    last_month_walked_format='Minulý mesiac ste prešli %d krokov',
    last_month_walked_info_format='Prešli ste %d km a spálili %d kcal',

    get_over_format=", okolo %d gramov tuku",
    click_to_get_help="Pozrite sa čo dokáže MiBand",
    take_a_walk="Prejdite sa s MiBand",
    take_a_walk_info="MiBand bude zaznamenávať vašu aktivitu a pomôže vám byť zdravý.",
    unlock_hint="Odomknite váš telefón s MiBand,",
    unlock_hint_info="objavte nový spôsob ochrany vášho súkromia.",
    no_data_hint_0="Hýbte sa a športujte pre vaše zdravie.",
    no_data_hint_1="Chcete byť stále šťastný? Zabehajte si.",
    no_data_hint_2="Kardio cvičenie vás osvieži a rozhýbe každý deň! ",
    no_data_hint_3="Bežný dospelý človek strávi 15%-20% spánku v hlbokej fáze. ",
    not_binded_hint="Nemáte prepojený MiBand s týmto účtom, prepojte ho teraz. ",
    new_record_info="WoW! Práve ste zdolali rekord v chôdzi.",
    new_record_format="Nový rekord, %d krokov, %s %d",
    today_goal_reached="Gratulujeme! Dosiahli ste váš dnešný cieľ. ",
    week_continue_reach_goal="Splnili ste váš denný cieľ po celý týždeň! To bol skvelý týždeň!",
    challenge_format="Dosiahli ste váš cieľ pre %d dní!",
    personal_best_format="Váš najväčší rekord je %d dní!",
    active_time_format_0="%dmin",
    active_time_format_1="%dh",
    active_time_format_2="%dh %dmin",
    activie_run_format_0="Zabehli ste %s. Skvelé!",
    activie_run_format_1="Zabehli ste %s. Len tak ďalej!",
    activie_run_format_2="Zabehli ste %s, Neskutočné!",
    activie_run_consumed="Spálili ste %d kcal. %s",
    continue_with_skips_title="Včera ste nedosiahli svoj cieľ. Nazvyme ho oddychový deň ;)",
    continue_with_skips_title_today="Nedosiahli ste dnes svoj cieľ. Nazvyme ho oddychový deň ;)",
    personal_best_with_skips_format="Máte už len %d oddychových dní ;)",
    continue_used_n_skips_format="Dosiahli ste svoj cieľ pre %d dní za sebou! Stále máte %d oddychových dní ;)",
    continue_used_0_skips_format="Dosiahli ste svoj cieľ pre %d dní za sebou! Nemali ste žiaden oddychový deň.",
    personal_best_on_skip_day_title="%d dňový rekord! Máte nárok na oddychový deň!",
    personal_best_on_skip_day_info="Po každom 7-dňovom dosiahnutí cieľa máte nárok na jeden oddychový deň.",
    manual_lazy_title="Nedosiahli ste dnes svoj cieľ, chcete ho nazvať oddychovým dňom?",
    manual_lazy_subtitle="The streak will cover up if you confirm.",
    manual_lazy_title_used="Dnes je oddychový deň, užite si ho!",
    manual_lazy_subtitle_used="The streak will be added one if you hit the goal later.",
    manual_fail_ytd_title = "Sorry, the streak broken yesterday.",
    manual_fail_ytd_subtitle = "Your streak until day before yesterday is %d.",
    unlock_password_hint="Nastavte zámok telefónu pre vašu bezpečnosť.",
    unlock_password_hint_info="MiBand je najlepší pre odomknutie.",

    get_distance_format=", celkovo %dm",
    activity_walk_format="%s Chôdza %d krokov %s",
    activity_walk_consumed_format="Spálené %d kcal %s",

    activity_rope_skipping_format="%s preskočené švihadlo %d krát",
    activity_situp_format="%s %d sed-ľah",
    activity_consumed_format="Spálené %dkcal %s",
    activity_activity_format="%s %s v pohybe %s",
    activity_activity_format_run="%s Cvičili ste %s, zabehli %s",
    last_night_sleeped_good_format="Minulú noc, ste spali %s. Skvelý spánok!",
    last_night_sleeped_normal_format="Minulú noc, ste spali %s",
    deep_sleep_format="Hlboká fáza spánku bola %s",

    battery_low_info="Batéria je vybitá, pripojte MiBand na nabíjačku.",
    battery_very_low_info="Pripojte na nabíjačku",

    cannot_find_bracelet="Nebolo možné nájsť váš MiBand?",
    cannot_find_bracelet_info="Uistite sa, že váš MiBand je nabitý a nachádza sa v blízkosti vášho telefónu.",
    challenge_to_get="%s dní od nového rekordu!",
    record_reach_max="Dosiahli ste svoj rekord!",
    new_record_born="Nový rekord!",
    select_devices="Vyberte zariadenie na prepojenie",
 
    ---====== Weather tips ===============
    weather_tips_title_0 = "Heavy pollution, try to stay indoors",
    weather_tips_title_1 = "Heavy pollution, try to stay indoors",
    weather_tips_info = "Sit-ups or jumping rope are great indoor exercises!",
    today_goal_reached_click_info="Stlačte pre zobrazenie výsledkov.",

    ---------------Weight scale -------------------
    welcome_use_weight_scale = "Vitajte v používaní váhy",
    welcome_use_weight_scale_not_bind = "stlačte pre prepojenie s váhou",
    welcome_use_mi_health="Vitajte v MiBand",
    daily_steps_not_comlete = "Stále je potrebných ešte %s krokov!"
 }

localization_Czech_table = {
    calories_table={
	{str="≈ Okurek (100g)", calories=14}, 
	{str="≈ Kuřecí vývar (100g)", calories=15}, 
	{str="≈ Kapusta (100g)", calories=16}, 
	{str="≈ Nakládaná rajčata (100g)", calories=19}, 
	{str="≈ Houby (100g)", calories=20}, 
	{str="≈ Ředkvičky (100g)", calories=21}, 
	{str="≈ Baklažán (100g)", calories=24}, 
	{str="≈ Dýně (100g)", calories=25}, 
	{str="≈ Kyselá kapusta (100g)", calories=25}, 
	{str="≈ Houbová polévka (100g)", calories=26}, 
	{str="≈ Brokolice (100g)", calories=27}, 
	{str="≈ Zeleninová polévka (100g)", calories=28}, 
	{str="≈ Jahody (100g)", calories=30}, 
	{str="≈ Boršč (100g)", calories=36}, 
	{str="≈ Masová polévka (100g)", calories=36}, 
	{str="≈ Červená řepa (100g)", calories=36}, 
	{str="≈ Jablka (100g)", calories=37}, 
	{str="≈ Pomeranč (100g)", calories=38}, 
	{str="≈ Bramborová polévka (100g)", calories=39}, 
	{str="≈ Meloun (100g)", calories=39}, 
	{str="≈ Šťavelová polévka (100g)", calories=40}, 
	{str="≈ Cmar 1% (100g)", calories=40}, 
	{str="≈ Coca-Cola (100g)", calories=42}, 
	{str="≈ 1,5% mléko (100g)", calories=45}, 
	{str="≈ Red Bull (100g)", calories=45}, 
	{str="≈ Polévka (100g)", calories=46}, 
	{str="≈ Broskev (100g)", calories=46}, 
	{str="≈ Sýr (25g)", calories=48}, 
	{str="≈ Třešně (100g)", calories=52}, 
	{str="≈ Pomerančový džus (100g)", calories=54}, 
	{str="≈ 3,2% mléko (100g)", calories=58}, 
	{str="≈ Ratatouille (100g)", calories=60}, 
	{str="≈ Bramborová kaše (100g)", calories=65}, 
	{str="≈ Hrachová polévka (100g)", calories=66}, 
	{str="≈ Mango (100g)", calories=67}, 
	{str="≈ Čočková polévka (100g)", calories=68}, 
	{str="≈ Jahodové želé (100g)", calories=69}, 
	{str="≈ Jogurt 1,5% (100g)", calories=70}, 
	{str="≈ Krabí tyčinky (100g)", calories=73}, 
	{str="≈ Squid (100g)", calories=75}, 
	{str="≈ Champagne (100g)", calories=76}, 
	{str="≈ Víno 13% (100g)", calories=78}, 
	{str="≈ Kapustový guláš (100g)", calories=81}, 
	{str="≈ Vařené brambory (100g)", calories=82}, 
	{str="≈ Absinthe 60% (100g)", calories=83}, 
	{str="≈ Bramborová kaše s mlékem (100g)", calories=85}, 
	{str="≈ Vařená vejce (55g)", calories=88}, 
	{str="≈ Banán (100g)", calories=89}, 
	{str="≈ Rajčatová fazole (100g)", calories=92}, 
	{str="≈ Kečup (100g)", calories=93}, 
	{str="≈ Rýže se zeleninou (100g)", calories=94}, 
	{str="≈ Toast (1 plátek)", calories=95}, 
	{str="≈ Tuňák (100g)", calories=96}, 
	{str="≈ Vařené walleye (100g)", calories=97}, 
	{str="≈ Zeleninový guláš (100g)", calories=99}, 
	{str="≈ Vařený kapr (100g)", calories=102}, 
	{str="≈ Ovocný salát (100g)", calories=103}, 
	{str="≈ Filet krocana (100g)", calories=104}, 
	{str="≈ Uzený jeseter (100g)", calories=105}, 
	{str="≈ Rýže (100g)", calories=113}, 
	{str="≈ Zeppelins (100g)", calories=117}, 
	{str="≈ Míchaná vejce", calories=119}, 
	{str="≈ Kaviár z kabačku (100g)", calories=122}, 
	{str="≈ Japonská majonéza (100g)", calories=134}, 
	{str="≈ Marshmallow (1ks)", calories=135},
	{str="≈ Cottage sýr (100g)", calories=136}, 
	{str="≈ Avocado", calories=140}, 
	{str="≈ Cappuccino (100g)", calories=140}, 
	{str="≈ Lobi (100g)", calories=141}, 
	{str="≈ Hovězí jazyk (100g)", calories=146}, 
	{str="≈ Hovězí guláš (100g)", calories=148}, 
	{str="≈ Vařený kuřecí řízek (100g)", calories=153}, 
	{str="≈ Smažené brambory (100g)", calories=154}, 
	{str="≈ Pizza Margarita (100g)", calories=157}, 
	{str="≈ Karbanátky (100g)", calories=159}, 
	{str="≈ Pohanka (100g)", calories=160}, 
	{str="≈ Žitný chléb (100g)", calories=165}, 
	{str="≈ Pečený krocan (100g)", calories=165}, 
	{str="≈ Uzené kuřecí (100g)", calories=184}, 
	{str="≈ Vepřové maso (100g)", calories=195}, 
	{str="≈ Klobása (100g)", calories=198},
	{str="≈ Losos (200g)", calories=201}, 
	{str="≈ Smetana 20% (100g)", calories=204}, 
	{str="≈ Krém (100g)", calories=206}, 
	{str="≈ Pasta Bolognese (100g)", calories=208}, 
	{str="≈ Černý chléb (100g)", calories=214}, 
	{str="≈ Kandované ovoce (100g)", calories=216}, 
	{str="≈ Slaneček (100g)", calories=217}, 
	{str="≈ Mushroom julienne (100g)", calories=219}, 
	{str="≈ Caesar salát (100g)", calories=221}, 
	{str="≈ Omeleta (100g)", calories=222}, 
	{str="≈ Světlé pivo (0,5l)", calories=225}, 
	{str="≈ Ovesný chléb (100g)", calories=226}, 
	{str="≈ Dušené jehněčí (100g)", calories=226}, 
	{str="≈ Sundae (100g)", calories=227}, 
	{str="≈ McD Hamburger", calories=229}, 
	{str="≈ Pečené vepřové (100g)", calories=233}, 
	{str="≈ Bílý chléb (100g)", calories=235}, 
	{str="≈ Pita chléb (100g)", calories=236}, 
	{str="≈ Vodka 40% (100g)", calories=237}, 
	{str="≈ Basturma (100g)", calories=240}, 
	{str="≈ Šunka italská (100g)", calories=241}, 
	{str="≈ Ravioli (100g)", calories=245}, 
	{str="≈ Červený kaviár (100g)", calories=249}, 
	{str="≈ Shawarma (100g)", calories=250}, 
	{str="≈ Kuřecí párky (100g)", calories=259}, 
	{str="≈ Karbanátky (100g)", calories=260}, 
	{str="≈ Rozinky (100g)", calories=262}, 
	{str="≈ McD Cheeseburger", calories=264}, 
	{str="≈ Klobásy (100g)", calories=270}, 
	{str="≈ Šunka (100g)", calories=270}, 
	{str="≈ Huňáčik uzený (100g)", calories=270}, 
	{str="≈ McD McNuggets (100g)", calories=272}, 
	{str="≈ Knedlík (100g)", calories=275}, 
	{str="≈ Grilovaný losos (100g)", calories=283}, 
	{str="≈ Černý kaviár (100g)", calories=289}, 
	{str="≈ Majonéza (100g)", calories=299}, 
	{str="≈ Med (100g)", calories=302}, 
	{str="≈ McD hranolky (100g)", calories=303}, 
	{str="≈ Termíny (100g)", calories=306}, 
	{str="≈ Jablečné palačinky (100g)", calories=306}, 
	{str="≈ Plněná kapusta (100g)", calories=311}, 
	{str="≈ Palačinky (100g)", calories=322}, 
	{str="≈ Omeleta se sýrem (100g)", calories=324}, 
	{str="≈ Játrový salám (100g)", calories=326}, 
	{str="≈ Šišky (100g)", calories=329}, 
	{str="≈ Cheesecake (100g)", calories=331}, 
	{str="≈ Lívance (100g)", calories=332}, 
	{str="≈ Kebab (100g)", calories=339}, 
	{str="≈ Špagety (100g)", calories=344}, 
	{str="≈ Muffin (100g)", calories=345}, 
	{str="≈ Perník (100g)", calories=350}, 
	{str="≈ Hovězí Stroganov (100g)", calories=355}, 
	{str="≈ Cornflakes (100g)", calories=363}, 
	{str="≈ Těstoviny (100g)", calories=371}, 
	{str="≈ Steak (100g)", calories=384}, 
	{str="≈ Suchary (100g)", calories=386}, 
	{str="≈ Cukr (100g)", calories=398}, 
	{str="≈ Ovesné sušenky (100g)", calories=440}, 
	{str="≈ Řízek (100g)", calories=456}, 
	{str="≈ Lasagne (100g)", calories=460}, 
	{str="≈ Foie gras (100g)", calories=462}, 
	{str="≈ Medovník (100g)", calories=478}, 
	{str="≈ Pop-corn (100g)", calories=480}, 
	{str="≈ Twix", calories=483}, 
	{str="≈ Snickers", calories=497}, 
	{str="≈ Slanina (100g)", calories=500}, 
	{str="≈ McD Big Mac", calories=510}, 
	{str="≈ Lays Max čipsy (100g)", calories=510}, 
	{str="≈ KitKat", calories=524}, 
	{str="≈ Tiramisu (100g)", calories=540}, 
	{str="≈ Pringles (100g)", calories=540}, 
	{str="≈ Čokoláda (100g)", calories=546}, 
	{str="≈ Napoleon torta (100g)", calories=552}, 
	{str="≈ Salám (100g)", calories=568}, 
	{str="≈ Pečená husa (100g)", calories=620}, 
	{str="≈ Smažený knedlík (100g)", calories=764}, 
	{str="≈ McD Big Tasty", calories=850}, 
    },

    ok='OK',

    hour='hod',
    minute='min',
    month='měsíc',
    day='den',
    step="krok",
    km='km',
    minute_format='%d min',
    hour_minute_format='%d h %d m',
    hour_format='%d h',

    welcome_use="Vítejte :)",
    last_week_walked_format='Minulý týden jste ušli %d kroků',
    last_week_walked_info_format='Ušli jste %d km a spálili %d kcal',
    last_month_walked_format='Minulý měsíc jste ušli %d kroků',
    last_month_walked_info_format='Ušli jste %d km a spálili %d kcal',
    unlock_password_hint="Nastavte zámok telefónu pre vašu bezpečnosť.",
    unlock_password_hint_info="MiBand je najlepší pre odomknutie.",

    get_over_format=", kolem %dg tuku",
    click_to_get_help="Mrkněte co dokáže MiBand",
    take_a_walk="Projděte se s MiBand",
    take_a_walk_info="MiBand bude zaznamenávat vaši aktivitu a pomůže vám být fit.",
    unlock_hint="Odemkněte váš telefon s MiBand,",
    unlock_hint_info="Objevte nový způsob ochrany vašeho soukromí.",
    no_data_hint_0="Hýbejte se a sportujte pro vaše zdraví.",
    no_data_hint_1="Chcete být stále šťastní? Zaběhejte si.",
    no_data_hint_2="Kardio cvičení vás osvěží a rozhýbe každý den! ",
    no_data_hint_3="Běžný dospělý člověk stráví 15-20% spánku v hluboké fázi. ",
    not_binded_hint="Nemáte propojený MiBand s tímto účtem, propojte jej nyní. ",
    new_record_info="WoW! Právě byl zdolán rekord v chůzi.",
    new_record_format="Nový rekord, %d kroků, %s %d",
    today_goal_reached="Gratulujeme! Byl dosažen váš dnešní cíl. ",
    week_continue_reach_goal="Za poslední týden byl každý den splněn váš cíl! Skvělý týden!",
    challenge_format="Byl dosažen váš %d denní cíl!",
    personal_best_format="Váš nejvyšší rekord je %d dní!",
    active_time_format_0="%d min",
    active_time_format_1="%d h",
    active_time_format_2="%d h %d min",
    activie_run_format_0="Uběhnuto %s. Skvělé!",
    activie_run_format_1="Uběhnuto %s. Jen tak dál!",
    activie_run_format_2="Uběhnuto %s, Neskutečné!",
    activie_run_consumed="Spáleno %d kcal. %s",
    continue_with_skips_title="Včera nebyl dosažen váš cíl. Celkem lenivý den ;)",
    continue_with_skips_title_today="Dnes nebyl dosažen váš cíl. Celkem odpočinkový den ;)",
    personal_best_with_skips_format="Máte už jen %d odpočinkových dní ;)",
    continue_used_n_skips_format="Byl dosažen váš cíl pro %d dní po sobě! Stále máte %d odpočinkových dní ;)",
    continue_used_0_skips_format="Byl dosažen váš cíl pro %d dní po sobě! Bez jediného odpočinkového dne.",
    personal_best_on_skip_day_title="%d denní rekord! Máte nárok na odpočinkový den!",
    personal_best_on_skip_day_info="Po každém 7-denním dosažení cíle, máte nárok na jeden odpočinkový den.",
    manual_lazy_title="Dnes nebyl dosažen váš cíl, chcete ho nazvat odpočinkovým dnem?",
    manual_lazy_subtitle="The streak will cover up if you confirm.",
    manual_lazy_title_used="Dnes je odpočinkový den, užijte si ho!",
    manual_lazy_subtitle_used="The streak will be added one if you hit the goal later.",
    manual_fail_ytd_title = "Sorry, the streak broken yesterday.",
    manual_fail_ytd_subtitle = "Your streak until day before yesterday is %d.",

    get_distance_format="celkem %d m",
    activity_walk_format="%s Chůze %d kroků %s",
    activity_walk_consumed_format="Spáleno %d kcal %s",

    activity_rope_skipping_format="%s přeskočeno švihadlo %d krát",
    activity_situp_format="%s %d sed-leh",
    activity_consumed_format="Spáleno %d kcal %s",
    activity_activity_format="%s %s v pohybu, %s",
    activity_activity_format_run="%s Cvičení %s, běhání %s",
    last_night_sleeped_good_format="Minulou noc trval spánek %s",
    last_night_sleeped_normal_format="Minulou noc trval spánek %s",
    deep_sleep_format="Hluboká fáze spánku trvala %s",

    battery_low_info="Baterie je vybitá, připojte MiBand na nabíječku.",
    battery_very_low_info="Připojte na nabíječku",

    cannot_find_bracelet="Nebylo možné najít váš MiBand?",
    cannot_find_bracelet_info="Ujistěte se, že váš MiBand je nabitý a nachází se v blízkosti vašeho telefonu.",
    challenge_to_get="%s dní od nového rekordu!",
    record_reach_max="Byl dosažen váš rekord!",
    new_record_born="Nový rekord!",
 }
localization_Polish_table = {
    calories_table={
        {str="≈ ogórek (100g)", calories=14}, 
        {str="≈ bulion z kurczaka (100g)", calories=15}, 
        {str="≈ porcja kapusty (100g)", calories=16}, 
        {str="≈ pomidory marynowane (100g)", calories=19}, 
        {str="≈ porcja grzybów (100g)", calories=20}, 
        {str="≈ rzodkiewka (100g)", calories=21}, 
        {str="≈ bakłażan (100g)", calories=24}, 
        {str="≈ dynia (100g)", calories=25}, 
        {str="≈ kapusta kiszona (100g)", calories=25}, 
        {str="≈ porcja pieczarek (100g)", calories=26}, 
        {str="≈ brokuły (100g)", calories=27}, 
        {str="≈ miska zupy (100g)", calories=28}, 
        {str="≈ truskawki (100g)", calories=30}, 
        {str="≈ barszcz (100g)", calories=36}, 
        {str="≈ zupa miso (100g)", calories=36}, 
        {str="≈ buraki (100g)", calories=36}, 
        {str="≈ jabłko (100g)", calories=37}, 
        {str="≈ pomarańcza (100g)", calories=38}, 
        {str="≈ zupa ziemniaczana (100g)", calories=39}, 
        {str="≈ arbuz (100g)", calories=39}, 
        {str="≈ zupa szczwiowa (100g)", calories=40}, 
        {str="≈ maślanka 1% (100g)", calories=40}, 
        {str="≈ Coca-Cola (100g)", calories=42}, 
        {str="≈ 1,5% mleko (100g)", calories=45}, 
        {str="≈ Red Bull (100g)", calories=45}, 
        {str="≈ Chowder (100g)", calories=46}, 
        {str="≈ brzoskwinia (100g)", calories=46}, 
        {str="≈ ser Hochland (25g)", calories=48}, 
        {str="≈ Cherry (100g)", calories=52}, 
        {str="≈ sok z pomarańczy (100g)", calories=54}, 
        {str="≈ 3,2% mleko (100g)", calories=58}, 
        {str="≈ Ratatuj (100g)", calories=60}, 
        {str="≈ ziemniaki puree (100g)", calories=65}, 
        {str="≈ porcja groszku (100g)", calories=66}, 
        {str="≈ mango (100g)", calories=67}, 
        {str="≈ zupa z soczewicy (100g)", calories=68}, 
        {str="≈ galaretka truskawkowa (100g)", calories=69}, 
        {str="≈ Jogurt 1,5% (100g)", calories=70}, 
        {str="≈ paluszki krabowe (100g)", calories=73}, 
        {str="≈ ośmiornica (100g)", calories=75}, 
        {str="≈ szampan (100g)", calories=76}, 
        {str="≈ wino 13% (100g)", calories=78}, 
        {str="≈ kapusta (100g)", calories=81}, 
        {str="≈ ziemniaki gotowane (100g)", calories=82}, 
        {str="≈ Absynt 60% (100g)", calories=83}, 
        {str="≈ tłuczone ziemniaki (100g)", calories=85}, 
        {str="≈ gotowane jajko (55g)", calories=88}, 
        {str="≈ banan (100g)", calories=89}, 
        {str="≈ sok pomidorowy (100g)", calories=92}, 
        {str="≈ ketchup (100g)", calories=93}, 
        {str="≈ ryż z warzywami (100g)", calories=94}, 
        {str="≈ tost (1)", calories=95}, 
        {str="≈ porcja tuńczyka (100g)", calories=96}, 
        {str="≈ gotowane walleye (100g)", calories=97}, 
        {str="≈ roślinny gulasz (100g)", calories=99}, 
        {str="≈ gotowana ryba (100g)", calories=102}, 
        {str="≈ sałatka owocowa (100g)", calories=103}, 
        {str="≈ filet z indyka (100g)", calories=104}, 
        {str="≈ wieprzowina (100g)", calories=105}, 
        {str="≈ porcja ryżu (100g)", calories=113}, 
        {str="≈ sterowce (100g)", calories=117}, 
        {str="≈ jajecznica", calories=119}, 
        {str="≈ squash (100g)", calories=122}, 
        {str="≈ japoński majonez (100g)", calories=134}, 
        {str="≈ kefir (1szt)", calories=135}, 
        {str="≈ twaróg (100g)", calories=136}, 
        {str="≈ awokado", calories=140}, 
        {str="≈ cappuccino (100g)", calories=140}, 
        {str="≈ Lobio (100g)", calories=141}, 
        {str="≈ język wołowy (100g)", calories=146}, 
        {str="≈ gulasz wołowy (100g)", calories=148}, 
        {str="≈ gotowany filet z kurczaka (100g)", calories=153}, 
        {str="≈ placki ziemniaczane (100g)", calories=154}, 
        {str="≈ pizza Margarita (100g)", calories=157}, 
        {str="≈ klopsiki (100g)", calories=159}, 
        {str="≈ kasza gryczana (100g)", calories=160}, 
        {str="≈ chleb żytni (100g)", calories=165}, 
        {str="≈ pieczeń z indyka (100g)", calories=165}, 
        {str="≈ kurczak wędzony (100g)", calories=184}, 
        {str="≈ cue wieprzowe (100g)", calories=195}, 
        {str="≈ kiełbaska (100g)", calories=198}, 
        {str="≈ porcja łososia (201g)", calories=201}, 
        {str="≈ śmietana 20% (100g)", calories=204}, 
        {str="≈ bita śmietana (100g)", calories=206}, 
        {str="≈ pasta Bolognese (100g)", calories=208}, 
        {str="≈ czarny chleb (100g)", calories=214}, 
        {str="≈ kandyzowane owoce (100g)", calories=216}, 
        {str="≈ śledź (100g)", calories=217}, 
        {str="≈ grzyb julienne (100g)", calories=219}, 
        {str="≈ sałatka cesarska (100g)", calories=221}, 
        {str="≈ omlet (100g)", calories=222}, 
        {str="≈ piwo (0,5 l)", calories=225}, 
        {str="≈ chleb owsiany (100g)", calories=226}, 
        {str="≈ gulasz jagnięcy (100g)", calories=226}, 
        {str="≈ Sundae (100g)", calories=227}, 
        {str="≈ hamburger z McDonalda", calories=229}, 
        {str="≈ pieczeń wieprzowa (100g)", calories=233}, 
        {str="≈ biały chleb (100g)", calories=235}, 
        {str="≈ chleb pita (100g)", calories=236}, 
        {str="≈ wódka 40% (100g)", calories=237}, 
        {str="≈ Basturma (100g)", calories=240}, 
        {str="≈ hamon (100g)", calories=241}, 
        {str="≈ ravioli (100g)", calories=245}, 
        {str="≈ kawior czerwony (100g)", calories=249}, 
        {str="≈ shawarma (100g)", calories=250}, 
        {str="≈ piersi z kurczaka (100g)", calories=259}, 
        {str="≈ kotlety (100g)", calories=260}, 
        {str="≈ rodzynki (100g)", calories=262}, 
        {str="≈ cheeseburger z McDonalda", calories=264}, 
        {str="≈ mleko (100g)", calories=270}, 
        {str="≈ szynka (100g)", calories=270}, 
        {str="≈ sardelki wędzone (100g)", calories=270}, 
        {str="≈ nuggetsy z McDonalda (100g)", calories=272}, 
        {str="≈ pierogi (100g)", calories=275}, 
        {str="≈ łosoś z grilla (100g)", calories=283}, 
        {str="≈ czarny kawior (100g)", calories=289}, 
        {str="≈ majonez (100g)", calories=299}, 
        {str="≈ miód (100g)", calories=302}, 
        {str="≈ frytki z McDonalda (100g)", calories=303}, 
        {str="≈ bataty (100g)", calories=306}, 
        {str="≈ naleśnik z jabłkiem (100g)", calories=306}, 
        {str="≈ gołąbki (100g)", calories=311}, 
        {str="≈ naleśniki (100g)", calories=322}, 
        {str="≈ omlet z serem (100g)", calories=324}, 
        {str="≈ kiełbasa (100g)", calories=326}, 
        {str="≈ pączki (100g)", calories=329}, 
        {str="≈ ciasto serowe (100g)", calories=331}, 
        {str="≈ naleśniki z masłem (100g)", calories=332}, 
        {str="≈ kebab (100g)", calories=339}, 
        {str="≈ spaghetti (100g)", calories=344}, 
        {str="≈ mufinka (100g)", calories=345}, 
        {str="≈ piernik (100g)", calories=350}, 
        {str="≈ befsztyk (100g)", calories=355}, 
        {str="≈ płatki śniadaniowe (100g)", calories=363}, 
        {str="≈ makaron (100g)", calories=371}, 
        {str="≈ stek (100g)", calories=384}, 
        {str="≈ krakersy (100g)", calories=386}, 
        {str="≈ porcja cukru (100g)", calories=398}, 
        {str="≈ płatki owsiane (100g)", calories=440}, 
        {str="≈ sznycel (100g)", calories=456}, 
        {str="≈ lasagne (100g)", calories=460}, 
        {str="≈ foie gras (100g)", calories=462}, 
        {str="≈ ciastko miodowe (100g)", calories=478}, 
        {str="≈ popcorn (100g)", calories=480}, 
        {str="≈ baton Twix", calories=483}, 
        {str="≈ baton Snickers", calories=497}, 
        {str="≈ bekon (100g)", calories=500}, 
        {str="≈ Big Mac z McDonalda", calories=510}, 
        {str="≈ Lays Max (100g)", calories=510}, 
        {str="≈ baton KitKat", calories=524}, 
        {str="≈ tiramisu (100g)", calories=540}, 
        {str="≈ Pringles (100g)", calories=540}, 
        {str="≈ tabliczka czekolady (100g)", calories=546}, 
        {str="≈ ciasto napoleon (100g)", calories=552}, 
        {str="≈ salami (100g)", calories=568}, 
        {str="≈ pieczona gęś (100g)", calories=620}, 
        {str="≈ smażone pierogi (100g)", calories=764}, 
        {str="≈ Big Tasty z McDonalda", calories=850}, 
    },

    ok='OK',

    hour='godz.',
    minute='min',
    month='miesiąc',
    day='dzień',
    step="krok",
    km='km',
    minute_format='%d min.',
    hour_minute_format='%d godz. %d min.',
    hour_format='%d godz.',

    welcome_use="Witaj, jestem MiOpaską",
    last_week_walked_format="W ostatnim tygodniu przeszedłeś %d kroków",
    last_week_walked_info_format="Przeszedłeś %d km, spalając %d kcal",
    last_month_walked_format="W ostatnim miesiącu przeszedłeś %d kroków",
    last_month_walked_info_format="Przeszedłeś %d km, spalając %d kcal",

    get_over_format=", ok. %d g tłuszczu",
    click_to_get_help="Sprawdź co jeszcze można robić z MiOpaską",
    take_a_walk="Idź na spacer z MiOpaską",
    take_a_walk_info="MiOpaska będzie śledzić Twoje aktywności i pomoże być zdrowszym",
    unlock_hint="Odblokuj telefon z MiOpaską",
    unlock_hint_info="Opaska może też odblokować telefon",
    no_data_hint_0="Uprawiaj sporty i dużo się ruszaj",
    no_data_hint_1="Chcesz pozostać szczęśliwy? Po prostu biegnij.",
    no_data_hint_2="Cardio workout will make you light and fresh every day! ",
    no_data_hint_3="Dorosłe osoby spędzają ok. 15%-20% snu w fazie głębokiej.",
    not_binded_hint="Nie powiązałeś jeszcze MiOpaski z kontem. Zrób to teraz. ",
    new_record_info="Gratulacje! Właśnie pobiłeś swój dzienny rekord ilości kroków.",
    new_record_format="Nowy rekord: %d kroków, %s %d",
    today_goal_reached="Gratulacje! Osiągnąłeś dzisiaj swój cel. ",
    week_continue_reach_goal="Osiągałeś rekordy codziennie, przez cały tydzień! Dobra robota!",
    challenge_format="Osiągnąłeś rekord w %d dni!",
    personal_best_format="Twój najwyższy rekord to %d dni!",
    continue_with_skips_title="You didn't hit your goal yesterday, don't worry, we have used a cheat note to cover you up ;)",
    personal_best_with_skips_format="Just made the highest record for %d days! Also, there are %d cheat notes left ;)",
    continue_used_n_skips_format="Osiągnięto cel w %d dni z rzędu. Masz jeszcze %d dni odpoczynku! ;)",
    continue_used_0_skips_format="Osiągnięto cel w %d dni z rzędu! Nie miałeś dnia na regenerację.",
    personal_best_on_skip_day_title="%d dzień z rekordem z rzędu! Masz prawo do dnia odpoczynku!",
    personal_best_on_skip_day_info="Po 7 dniach z rzędu kiedy osiągasz cel możesz wziąć dzień odpoczynku",

    active_time_format_0="%d min",
    active_time_format_1="%d godz.",
    active_time_format_2="%d godz. %d min",
    activie_run_format_0="Przebiegłeś %s. Dobra robota!",
    activie_run_format_1="Przebiegłeś %s. Dobrze ci idzie!",
    activie_run_format_2="Przebiegłeś %s. Niesamowita wytrzymałość!",
    activie_run_consumed="Spalonych %d kcal. %s",

    continue_with_skips_title="Wczoraj nie udało się osiągnąć celu. Nazwijmy to dniem relaksu ;).",
    continue_with_skips_title_today="Nie udało się dziś osiągnąć celu. Niech będzie to dzień relaksu ;).",
    personal_best_with_skips_format="Masz tylko %d dni odpoczynku ;)",
    manual_lazy_title="Nie osiągnąłeś dziś celu. Czyżby dzień lenistwa?",
    manual_lazy_subtitle="Leniwy dzień",
    manual_lazy_title_used="Dzisiaj jest dzień odpoczynku!",
    manual_lazy_subtitle_used="passa zostanie dodany jeden jeśli trafisz do celu później.",
    manual_fail_ytd_title="Dobre wyniki przerwane",
    manual_fail_ytd_subtitle="Nie osiągasz swoich celów od %d dni.",
    unlock_password_hint="Ustaw blokadę telefonu.",
    unlock_password_hint_info="MiOpaska może blokować dostęp do telefonu.",

    get_distance_format="%d m.",
    activity_walk_format="%s przeszedłeś %d kroków, %s",
    activity_walk_consumed_format="Spalonych kalorii: %d kcal %s",

    activity_rope_skipping_format="%s %d podskoków",
    activity_situp_format="%s %d skłonów",
    activity_consumed_format="Spalonych %d kcal %s",

    activity_activity_format="%s: %s, dystans: %s",
    activity_activity_format_run="%s: %s, w biegu: %s",
    last_night_sleeped_good_format="Ostatniej nocy spałeś przez %s",
    last_night_sleeped_normal_format="Ostatniej nocy spałeś przez %s",
    deep_sleep_format="Czas spędzony w głębokim śnie: %s",

    battery_low_info="Niski stan baterii. Naładuj opaskę.",
    battery_very_low_info="Podłącz do ładowania",

    cannot_find_bracelet="Nie możesz znaleść opaski?",
    cannot_find_bracelet_info="Upewnij się, że MiOpaska jest naładowana i jest w pobliżu",

    challenge_to_get="%s dni od pobicia nowego rekordu!",
    record_reach_max="Pobiłeś swój najwyższy rekord!",
    new_record_born="Nowy rekord!",

    ---====== Weather tips ===============
    weather_tips_title_0 = "Heavy pollution, try to stay indoor.",
    weather_tips_title_1 = "Heavy pollution, try to stay indoor.",
    weather_tips_info = "Situps, rope skipping and plank are great indoor sports!",

    today_goal_reached_click_info="Dotknij by zobaczyć szczegóły",

    ---------------Weight scale -------------------
    welcome_use_weight_scale = "Welcome use weight scale",
    welcome_use_weight_scale_not_bind = "Click to bind weight scale",
    welcome_use_mi_health="Witaj w MiOpasce",

    select_devices="Wybierz urządzenia do powiązania z opaską",
    daily_steps_not_comlete = "Do celu brakuje %s kroków!"
 }

localization_Croatian_table = {
    calories_table={
        {str="≈ Krastavac (100g)",   calories=14},
        {str="≈ Pileća juha (100g)",  calories=15},
        {str="≈ Kupus (100g)",    calories=16},
        {str="≈ Ukiseljene rajčice (100g)",   calories=19},
        {str="≈ Gljive (100g)",  calories=20},
        {str="≈ Rotkvice (100g)",   calories=21},
        {str="≈ Patlidžan (100g)",   calories=24},
        {str="≈ Tikva (100g)",    calories=25},
        {str="≈ Kiseli kupus (100g)", calories=25},
        {str="≈ Juha od gljiva (100g)",  calories=26},
        {str="≈ Brokula (100g)",   calories=27},
        {str="≈ Veget. juha (100g)", calories=28},
        {str="≈ Jagode (100g)",   calories=30},
        {str="≈ Boršč (100g)", calories=36},
        {str="≈ juha (100g)",  calories=36},
        {str="≈ Cikla (100g)",   calories=36},
        {str="≈ Jabuka (100g)",  calories=37},
        {str="≈ Naranča (100g)", calories=38},
        {str="≈ Juha od rajčice (100g)",    calories=39},
        {str="≈ Lubenica (100g)", calories=39},
        {str="≈ Kisela juha (100g)",    calories=40},
        {str="≈ Mlaćenica 1% (100g)",  calories=40},
        {str="≈ Coca-Cola (100g)",  calories=42},
        {str="≈ 1.5% Mlijeko (100g)",  calories=45},
        {str="≈ Red Bull (100g)",   calories=45},
        {str="≈ Juha od školjaka (100g)",    calories=46},
        {str="≈ Breskva (100g)",  calories=46},
        {str="≈ Hochland sir (25g)", calories=48},
        {str="≈ Trešnja (100g)", calories=52},
        {str="≈ Sok od naranče (100g)",   calories=54},
        {str="≈ 3.2% mlijeko (100g)",  calories=58},
        {str="≈ Ratatouille (100g)",    calories=60},
        {str="≈ Pire krumpir (100g)",    calories=65},
        {str="≈ Juha od graška (100g)",   calories=66},
        {str="≈ Mango (100g)",  calories=67},
        {str="≈ Juha od leće (100g)",    calories=68},
        {str="≈ Žele od jagoda (100g)",   calories=69},
        {str="≈ Jogurt 1.5% (100g)",    calories=70},
        {str="≈ Račji štapići (100g)",    calories=73},
        {str="≈ Lignje (100g)",  calories=75},
        {str="≈ Šampanjac (100g)",  calories=76},
        {str="≈ Vino 13% (100g)",   calories=78},
        {str="≈ Gulaš od kupusa (100g)",    calories=81},
        {str="≈ Kuhani krumpir (100g)",    calories=82},
        {str="≈ Pelin 60% ​​(100g)", calories=83},
        {str="≈ Pire krumpir s mlijekom (100g)",   calories=85},
        {str="≈ Kuhano jaje (55g)",  calories=88},
        {str="≈ Banana (100g)", calories=89},
        {str="≈ Grah s rajčicom (100g)",   calories=92},
        {str="≈ Ketchup (100g)",    calories=93},
        {str="≈ Riža s povrćem (100g)",   calories=94},
        {str="≈ Dvopek (1 šnita)", calories=95},
        {str="≈ Tuna (100g)",   calories=96},
        {str="≈ Kuhani walleye (100g)", calories=97},
        {str="≈ Složenac od povrća (100g)", calories=99},
        {str="≈ Kuhani šaran (100g)",    calories=102},
        {str="≈ Voćna salata (100g)",    calories=103},
        {str="≈ Pureći odrezak (100g)",  calories=104},
        {str="≈ Sturgoen od svinjetine (100g)",  calories=105},
        {str="≈ Riža (100g)",   calories=113},
        {str="≈ Zeppelini (100g)",  calories=117},
        {str="≈ Kajgana", calories=119},
        {str="≈ Pasta od tikve (100g)",   calories=122},
        {str="≈ Japanska majoneza (100g)",    calories=134},
        {str="≈ Marshmallow (1pc)", calories=135},
        {str="≈ Cottage sir (100g)", calories=136},
        {str="≈ Avocado roll",  calories=140},
        {str="≈ Cappuccino (100g)", calories=140},
        {str="≈ Lobio (100g)",  calories=141},
        {str="≈ Goveđi jezik (100g)",    calories=146},
        {str="≈ Goveđi gulaš (100g)",   calories=148},
        {str="≈ Kuhani pileći odrezakt (100g)",  calories=153},
        {str="≈ Prženi krumpir (100g)",   calories=154},
        {str="≈ Pizza Margarita (100g)",    calories=157},
        {str="≈ Mesne okruglice (100g)",  calories=159},
        {str="≈ Heljda (100g)",  calories=160},
        {str="≈ Raženi kruh (100g)",  calories=165},
        {str="≈ Pečena puretina (100g)",   calories=165},
        {str="≈ Dimljena piletina (100g)", calories=184},
        {str="≈ Svinjski odrezak (100g)",   calories=195},
        {str="≈ Kobasice (100g)",   calories=198},
        {str="≈ Losos (201g)", calories=201},
        {str="≈ Šlag 20% (100g)", calories=204},
        {str="≈ Vrhnje (100g)",  calories=206},
        {str="≈ Pasta Bolognese (100g)",    calories=208},
        {str="≈ Crni kruh (100g)",    calories=214},
        {str="≈ Kandirano voće (100g)", calories=216},
        {str="≈ Slane haringe (100g)", calories=217},
        {str="≈ Gljive julienne (100g)",  calories=219},
        {str="≈ Cezar salata (100g)",   calories=221},
        {str="≈ Omelet (100g)",   calories=222},
        {str="≈ Svijetlo pivo (0.5L)", calories=225},
        {str="≈ Zobeni kruh (100g)",  calories=226},
        {str="≈ Jagnjeći ragu (100g)",  calories=226},
        {str="≈ Sundae (100g)", calories=227},
        {str="≈ McD Hamburger", calories=229},
        {str="≈ Pečena svinjetina (100g)", calories=233},
        {str="≈ Bijeli kruh (100g)",    calories=235},
        {str="≈ Pita kruh (100g)", calories=236},
        {str="≈ Votka 40% (100g)",  calories=237},
        {str="≈ Basturma (100g)",   calories=240},
        {str="≈ Hamon (100g)",  calories=241},
        {str="≈ Ravioli (100g)",    calories=245},
        {str="≈ Crveni kavijar (100g)", calories=249},
        {str="≈ Shawarma (100g)",   calories=250},
        {str="≈ Pileća salama (100g)",   calories=259},
        {str="≈ Kotleti (100g)",    calories=260},
        {str="≈ Grožđice (100g)",    calories=262},
        {str="≈ McD Cheeseburger",  calories=264},
        {str="≈ Kobasice s mlijekom (100g)",  calories=270},
        {str="≈ Šunka (100g)",    calories=270},
        {str="≈ Dimljeni Capelin (100g)", calories=270},
        {str="≈ McD McNuggets (100g)",  calories=272},
        {str="≈ Kosos na žaru (100g)", calories=283},
        {str="≈ Crni kavijar (100g)",   calories=289},
        {str="≈ Majoneza (100g)", calories=299},
        {str="≈ Med (100g)",  calories=302},
        {str="≈ McD Fries (100 g)", calories=303},
        {str="≈ Dates (100g)",  calories=306},
        {str="≈ Palačinke s ajbukama (100g)", calories=306},
        {str="≈ Punjeni kupus (100g)",    calories=311},
        {str="≈ Palačinke (100g)",   calories=322},
        {str="≈ Omelet s sirom (100g)", calories=324},
        {str="≈ Jetrena kobasica (100g)", calories=326},
        {str="≈ Krafne (100g)", calories=329},
        {str="≈ Torta od sira (100g)", calories=331},
        {str="≈ Palačinke s maslacem (100g)",   calories=332},
        {str="≈ Kebab (100g)",  calories=339},
        {str="≈ Špagete (100g)",  calories=344},
        {str="≈ Muffin (100g)", calories=345},
        {str="≈ Medenjak (100g)",    calories=350},
        {str="≈ Govedina stroganoff (100g)",    calories=355},
        {str="≈ Kukuruzne pahuljice (100g)", calories=363},
        {str="≈ Tjestenina (100g)",  calories=371},
        {str="≈ Odrezak (100g)",  calories=384},
        {str="≈ Krekeri (100g)",   calories=386},
        {str="≈ Šećer (100g)",  calories=398},
        {str="≈ Kolač od zobene kaše (100g)",    calories=440},
        {str="≈ Šnicla (100g)",  calories=456},
        {str="≈ Lazanje (100g)",    calories=460},
        {str="≈ Foie Gras (100g)",  calories=462},
        {str="≈ Kolač od meda (100g)", calories=478},
        {str="≈ Kokice (100g)",    calories=480},
        {str="≈ Twix",  calories=483},
        {str="≈ Snickers",  calories=497},
        {str="≈ Špek (100g)",  calories=500},
        {str="≈ McD Big Mac",   calories=510},
        {str="≈ Lays Max čips (100g)", calories=510},
        {str="≈ KitKat",    calories=524},
        {str="≈ Tiramisu (100g)",   calories=540},
        {str="≈ Pringles (100g)",   calories=540},
        {str="≈ Čokolada (100g)",  calories=546},
        {str="≈ Kolač Napoleon (100g)",  calories=552},
        {str="≈ Salama (100g)", calories=568},
        {str="≈ Pečena guska (100g)",    calories=620},
        {str="≈ Pržene okruglice (100g)",    calories=764},
        {str="≈ McD Big Tasty", calories=850},
    },

    ok='U redu',

    hour='sati',
    minute='min',
    month='mjesec',
    day='dan',
    step="koraka",
    km='km',
    mile='milja',
    minute_format='%dmin',
    hour_minute_format='%ds %dm',
    hour_format='%d sati',

    welcome_use="Dobrodošli",
    last_week_walked_format='Prošli tjedan prohodali ste %d koraka.',
    last_week_walked_info_format='Prohodano %d km, potrošeno %d kal.',
    last_month_walked_format='Prošli mjesec prohodali ste %d koraka.',
    last_month_walked_info_format='Prohodano %d km, potrošeno %d kal.',

    get_over_format=", oko %d grama ili masti.",
    click_to_get_help="Naučite više o Mi Bandu",
    take_a_walk="Prošetajte s vašim Mi Bandom",
    take_a_walk_info="Vaš Miband evidentira svaki vaš korak tijekom dana.",
    unlock_hint="Otključajte svoj telefon s MiBandom!",
    unlock_hint_info="Otkrijte novi način zaštite vaše privatnosti.",
    unlock_password_hint="Postavite zaključavanje zaslona kako bi telefon bio siguran.",
    unlock_password_hint_info="Mi Band pruža najbolje otključavanje zaslona.",
    no_data_hint_0="Nastavite se kretati, neka sport postane dijelom vašeg života.",
    no_data_hint_1="Ponavljanje je otac uspjeha.",
    no_data_hint_2="Težite napretku, a ne savršenstvu.",
    no_data_hint_3="Normalna odrasla osoba troši 15% -20% ukupnog vremena sna u dubokoj fazi sna. ",
    not_binded_hint="Nijedan Mi Band nije uparen s ovim računom. ",
    not_binded_hint_info="Također možete kliknuti na Vaga u izborniku.",
    new_record_info="Postigli ste novi rekord.",
    new_record_format="%d koraka, %s %d",
    today_goal_reached="Postigli ste svoj cilj za danas!",
    today_goal_reached_click_info="Kliknite za prikaz detalja.",
    week_continue_reach_goal="Vi",

    challenge_format="Postigli ste svoj cilj %d dana za redom!",
    personal_best_format="Vaš najveći rekord je %d dana!",
    continue_with_skips_title="Niste postigli svoj cilj jučer. Nazovimo ga Dan ljenčarenja ;)",
    continue_with_skips_title_today="Niste postigli svoj cilj danas. Nazovimo ga Dan ljenčarenja ;)",
    personal_best_with_skips_format="Preostalo vam je %d Dana ljenčarenja ;)",
    continue_used_n_skips_format="Postigli ste svoj cilj %d dana za redom! Još imate %d Dan ljenčarenja ;)",
    continue_used_0_skips_format="Postigli ste svoj cilj %d dana za redom! Nemate više preostalih Dana ljenčarenja.",
    personal_best_on_skip_day_title="%d dan post. cilja! Zaslužili ste Dan ljenčarenja!",
    personal_best_on_skip_day_info="Nakon 7-dnevnog postizanja cilja za redom, zaslužili ste Dan ljenčarenja. To će pokriti propuštene ciljeve automatski.",
    manual_lazy_title="Niste postigli svoj cilj danas.",
    manual_lazy_subtitle="Vaš cilj će se nastaviti, ako ste označili danas kao Dan ljenčarenja.",
    manual_lazy_title_used="Danas je Dan ljenčarenja.",
    manual_lazy_subtitle_used="Možete zaraditi više Dana ljenčarenja obaranjem osobnih rekorda.",
    manual_fail_ytd_title = "Završili ste svoj niz jučer.",
    manual_fail_ytd_subtitle = "Postizanje niza je dugačak %d.",

    active_time_format_0="%dm",
    active_time_format_1="%ds",
    active_time_format_2="%ds %dm",
    activie_run_format_0="Trčali ste %s. Jako dobro!",
    activie_run_format_1="Trčali ste %s, Odlično!",
    activie_run_format_2="Trčali ste %s.",
    activie_run_consumed="Potrošeno %dcal. %s",

    get_distance_format="oko %dm.",
    get_distance_format_british="%d inches",
    activity_walk_format="%s Prohodano %d koraka %s",
    activity_walk_consumed_format="Potrošeno %dkal%s.",
    activity_rope_skipping_format="%s preskakanje užeta %d puta",
    activity_situp_format="%s %d trbušnjaka",
    activity_consumed_format="Potrošeno %dcal %s",
    activity_activity_format="%s Vježbano %s %s",
    activity_activity_format_run="%s Vježbano %s, trčano %s",
    last_night_sleeped_good_format="Prošle noći spavali ste %s.",
    last_night_sleeped_normal_format="Prošle noći spavali ste %s.",
    deep_sleep_format="Faza dubokog sna je bila %.",

    battery_low_info="Stavite Mi Band na punjenje.",
    battery_very_low_info="Baterija banda je skoro prazna.",

    cannot_find_bracelet="Ne možete pronaći svoj Mi Band?",
    cannot_find_bracelet_info="Uvjerite se da je baterija vašeg MiBanda napunjena.",

    bracelet_disconnect = "Ne mogžete se povezati? Kliknite za pomoć.",

    challenge_to_get="%s dana od postizanja novog rekorda!",
    record_reach_max="Izjednačili ste svoj postojeći rekord!",
    new_record_born="Postigli ste novi rekord!",

	   ------====== Weather tips ===============
    weather_tips_title_0 = "Heavy pollution, try to stay indoors",
    weather_tips_title_1 = "Heavy pollution, try to stay indoors",
    weather_tips_info = "Sit-ups or jumping rope are great indoor exercises!",

    ---------------Weight scale -------------------
    welcome_use_weight_scale = "Dobrodošli u korištenje vage",
    welcome_use_weight_scale_not_bind = "Kliknite da povežete vage",
    welcome_use_mi_health="Dobrodošli u korištenje MiBanda",

    select_devices="Odaberite uređaje za uparivanje",
    daily_steps_not_comlete = "%s preostalo koraka"
 }
