-------------------------
-- Croatian Localization String resources
-- www.miui.website (2014)
-- MASVA
-------------------------
localization_hr_rHR_table = {
    calories_table={
        {str="≈ Krastavac (100g)",   calories=14},
        {str="≈ Pileća juha (100g)",  calories=15},
        {str="≈ Kupus (100g)",    calories=16},
        {str="≈ Ukiseljene rajčice (100g)",   calories=19},
        {str="≈ Gljive (100g)",  calories=20},
        {str="≈ Rotkvice (100g)",   calories=21},
        {str="≈ Patlidžan (100g)",   calories=24},
        {str="≈ Tikva (100g)",    calories=25},
        {str="≈ Kiseli kupus (100g)", calories=25},
        {str="≈ Juha od gljiva (100g)",  calories=26},
        {str="≈ Brokula (100g)",   calories=27},
        {str="≈ Veget. juha (100g)", calories=28},
        {str="≈ Jagode (100g)",   calories=30},
        {str="≈ Boršč (100g)", calories=36},
        {str="≈ juha (100g)",  calories=36},
        {str="≈ Cikla (100g)",   calories=36},
        {str="≈ Jabuka (100g)",  calories=37},
        {str="≈ Naranča (100g)", calories=38},
        {str="≈ Juha od rajčice (100g)",    calories=39},
        {str="≈ Lubenica (100g)", calories=39},
        {str="≈ Kisela juha (100g)",    calories=40},
        {str="≈ Mlaćenica 1% (100g)",  calories=40},
        {str="≈ Coca-Cola (100g)",  calories=42},
        {str="≈ 1.5% Mlijeko (100g)",  calories=45},
        {str="≈ Red Bull (100g)",   calories=45},
        {str="≈ Juha od školjaka (100g)",    calories=46},
        {str="≈ Breskva (100g)",  calories=46},
        {str="≈ Hochland sir (25g)", calories=48},
        {str="≈ Trešnja (100g)", calories=52},
        {str="≈ Sok od naranče (100g)",   calories=54},
        {str="≈ 3.2% mlijeko (100g)",  calories=58},
        {str="≈ Ratatouille (100g)",    calories=60},
        {str="≈ Pire krumpir (100g)",    calories=65},
        {str="≈ Juha od graška (100g)",   calories=66},
        {str="≈ Mango (100g)",  calories=67},
        {str="≈ Juha od leće (100g)",    calories=68},
        {str="≈ Žele od jagoda (100g)",   calories=69},
        {str="≈ Jogurt 1.5% (100g)",    calories=70},
        {str="≈ Račji štapići (100g)",    calories=73},
        {str="≈ Lignje (100g)",  calories=75},
        {str="≈ Šampanjac (100g)",  calories=76},
        {str="≈ Vino 13% (100g)",   calories=78},
        {str="≈ Gulaš od kupusa (100g)",    calories=81},
        {str="≈ Kuhani krumpir (100g)",    calories=82},
        {str="≈ Pelin 60% ​​(100g)", calories=83},
        {str="≈ Pire krumpir s mlijekom (100g)",   calories=85},
        {str="≈ Kuhano jaje (55g)",  calories=88},
        {str="≈ Banana (100g)", calories=89},
        {str="≈ Grah s rajčicom (100g)",   calories=92},
        {str="≈ Ketchup (100g)",    calories=93},
        {str="≈ Riža s povrćem (100g)",   calories=94},
        {str="≈ Dvopek (1 šnita)", calories=95},
        {str="≈ Tuna (100g)",   calories=96},
        {str="≈ Kuhani walleye (100g)", calories=97},
        {str="≈ Složenac od povrća (100g)", calories=99},
        {str="≈ Kuhani šaran (100g)",    calories=102},
        {str="≈ Voćna salata (100g)",    calories=103},
        {str="≈ Pureći odrezak (100g)",  calories=104},
        {str="≈ Sturgoen od svinjetine (100g)",  calories=105},
        {str="≈ Riža (100g)",   calories=113},
        {str="≈ Zeppelini (100g)",  calories=117},
        {str="≈ Kajgana", calories=119},
        {str="≈ Pasta od tikve (100g)",   calories=122},
        {str="≈ Japanska majoneza (100g)",    calories=134},
        {str="≈ Marshmallow (1pc)", calories=135},
        {str="≈ Cottage sir (100g)", calories=136},
        {str="≈ Avocado roll",  calories=140},
        {str="≈ Cappuccino (100g)", calories=140},
        {str="≈ Lobio (100g)",  calories=141},
        {str="≈ Goveđi jezik (100g)",    calories=146},
        {str="≈ Goveđi gulaš (100g)",   calories=148},
        {str="≈ Kuhani pileći odrezakt (100g)",  calories=153},
        {str="≈ Prženi krumpir (100g)",   calories=154},
        {str="≈ Pizza Margarita (100g)",    calories=157},
        {str="≈ Mesne okruglice (100g)",  calories=159},
        {str="≈ Heljda (100g)",  calories=160},
        {str="≈ Raženi kruh (100g)",  calories=165},
        {str="≈ Pečena puretina (100g)",   calories=165},
        {str="≈ Dimljena piletina (100g)", calories=184},
        {str="≈ Svinjski odrezak (100g)",   calories=195},
        {str="≈ Kobasice (100g)",   calories=198},
        {str="≈ Losos (201g)", calories=201},
        {str="≈ Šlag 20% (100g)", calories=204},
        {str="≈ Vrhnje (100g)",  calories=206},
        {str="≈ Pasta Bolognese (100g)",    calories=208},
        {str="≈ Crni kruh (100g)",    calories=214},
        {str="≈ Kandirano voće (100g)", calories=216},
        {str="≈ Slane haringe (100g)", calories=217},
        {str="≈ Gljive julienne (100g)",  calories=219},
        {str="≈ Cezar salata (100g)",   calories=221},
        {str="≈ Omelet (100g)",   calories=222},
        {str="≈ Svijetlo pivo (0.5L)", calories=225},
        {str="≈ Zobeni kruh (100g)",  calories=226},
        {str="≈ Jagnjeći ragu (100g)",  calories=226},
        {str="≈ Sundae (100g)", calories=227},
        {str="≈ McD Hamburger", calories=229},
        {str="≈ Pečena svinjetina (100g)", calories=233},
        {str="≈ Bijeli kruh (100g)",    calories=235},
        {str="≈ Pita kruh (100g)", calories=236},
        {str="≈ Votka 40% (100g)",  calories=237},
        {str="≈ Basturma (100g)",   calories=240},
        {str="≈ Hamon (100g)",  calories=241},
        {str="≈ Ravioli (100g)",    calories=245},
        {str="≈ Crveni kavijar (100g)", calories=249},
        {str="≈ Shawarma (100g)",   calories=250},
        {str="≈ Pileća salama (100g)",   calories=259},
        {str="≈ Kotleti (100g)",    calories=260},
        {str="≈ Grožđice (100g)",    calories=262},
        {str="≈ McD Cheeseburger",  calories=264},
        {str="≈ Kobasice s mlijekom (100g)",  calories=270},
        {str="≈ Šunka (100g)",    calories=270},
        {str="≈ Dimljeni Capelin (100g)", calories=270},
        {str="≈ McD McNuggets (100g)",  calories=272},
        {str="≈ Kosos na žaru (100g)", calories=283},
        {str="≈ Crni kavijar (100g)",   calories=289},
        {str="≈ Majoneza (100g)", calories=299},
        {str="≈ Med (100g)",  calories=302},
        {str="≈ McD Fries (100 g)", calories=303},
        {str="≈ Dates (100g)",  calories=306},
        {str="≈ Palačinke s ajbukama (100g)", calories=306},
        {str="≈ Punjeni kupus (100g)",    calories=311},
        {str="≈ Palačinke (100g)",   calories=322},
        {str="≈ Omelet s sirom (100g)", calories=324},
        {str="≈ Jetrena kobasica (100g)", calories=326},
        {str="≈ Krafne (100g)", calories=329},
        {str="≈ Torta od sira (100g)", calories=331},
        {str="≈ Palačinke s maslacem (100g)",   calories=332},
        {str="≈ Kebab (100g)",  calories=339},
        {str="≈ Špagete (100g)",  calories=344},
        {str="≈ Muffin (100g)", calories=345},
        {str="≈ Medenjak (100g)",    calories=350},
        {str="≈ Govedina stroganoff (100g)",    calories=355},
        {str="≈ Kukuruzne pahuljice (100g)", calories=363},
        {str="≈ Tjestenina (100g)",  calories=371},
        {str="≈ Odrezak (100g)",  calories=384},
        {str="≈ Krekeri (100g)",   calories=386},
        {str="≈ Šećer (100g)",  calories=398},
        {str="≈ Kolač od zobene kaše (100g)",    calories=440},
        {str="≈ Šnicla (100g)",  calories=456},
        {str="≈ Lazanje (100g)",    calories=460},
        {str="≈ Foie Gras (100g)",  calories=462},
        {str="≈ Kolač od meda (100g)", calories=478},
        {str="≈ Kokice (100g)",    calories=480},
        {str="≈ Twix",  calories=483},
        {str="≈ Snickers",  calories=497},
        {str="≈ Špek (100g)",  calories=500},
        {str="≈ McD Big Mac",   calories=510},
        {str="≈ Lays Max čips (100g)", calories=510},
        {str="≈ KitKat",    calories=524},
        {str="≈ Tiramisu (100g)",   calories=540},
        {str="≈ Pringles (100g)",   calories=540},
        {str="≈ Čokolada (100g)",  calories=546},
        {str="≈ Kolač Napoleon (100g)",  calories=552},
        {str="≈ Salama (100g)", calories=568},
        {str="≈ Pečena guska (100g)",    calories=620},
        {str="≈ Pržene okruglice (100g)",    calories=764},
        {str="≈ McD Big Tasty", calories=850},
    },

    ok='U redu',

    hour='sati',
    minute='min',
    month='mjesec',
    day='dan',
    step="koraka",
    km='km',
    mile='milja',
    minute_format='%dmin',
    hour_minute_format='%ds %dm',
    hour_format='%d sati',

    welcome_use="Dobrodošli",
    last_week_walked_format='Prošli tjedan prohodali ste %d koraka.',
    last_week_walked_info_format='Prohodano %d km, potrošeno %d kal.',
    last_month_walked_format='Prošli mjesec prohodali ste %d koraka.',
    last_month_walked_info_format='Prohodano %d km, potrošeno %d kal.',

    get_over_format=", oko %d grama ili masti.",
    click_to_get_help="Naučite više o Mi Bandu",
    take_a_walk="Prošetajte s vašim Mi Bandom",
    take_a_walk_info="Vaš Miband evidentira svaki vaš napravljeni korak tijekom dana.",
    unlock_hint="Otključajte svoj telefon!",
    unlock_hint_info="Otkrijte novi način zaštite vaše privatnosti.",
    unlock_password_hint="Postavite zaključavanje zaslona kako bi telefon bio siguran.",
    unlock_password_hint_info="Mi Band pruža najbolje otključavanje zaslona.",
    no_data_hint_0="Nastavite se kretati, neka sport postane dijelom vašeg života.",
    no_data_hint_1="Ponavljanje je otac uspjeha.",
    no_data_hint_2="Težite napretku, a ne savršenstvu.",
    no_data_hint_3="Bez obzira na to koliko stee sporo, još uvijek ste brži od onih koji se izležavaju na kauču.",
    not_binded_hint="Nijedan Mi Band nije uparen s ovim računom. ",
    not_binded_hint_info="Također možete kliknuti na Vaga u izborniku.",
    new_record_info="Postigli ste novi rekord.",
    new_record_format="%d koraka, %s %d",
    today_goal_reached="Postigli ste svoj cilj za danas!",
    today_goal_reached_click_info="Kliknite za prikaz detalja.",
    week_continue_reach_goal="Vi",

    challenge_format="Postigli ste svoj cilj %d dana za redom!",
    personal_best_format="Vaš najveći rekord je %d dana!",
    continue_with_skips_title="Niste postigli svoj cilj jučer. Nazovimo ga Dan ljenčarenja ;)",
    continue_with_skips_title_today="Niste postigli svoj cilj danas. Nazovimo ga Dan ljenčarenja ;)",
    personal_best_with_skips_format="Preostalo vam je %d Dana ljenčarenja ;)",
    continue_used_n_skips_format="Postigli ste svoj cilj %d dana za redom! Još imate %d Dan ljenčarenja ;)",
    continue_used_0_skips_format="Postigli ste svoj cilj %d dana za redom! Nemate više preostalih Dana ljenčarenja.",
    personal_best_on_skip_day_title="%d dan post. cilja! Zaslužili ste Dan ljenčarenja!",
    personal_best_on_skip_day_info="Nakon 7-dnevnog postizanja cilja za redom, zaslužili ste Dan ljenčarenja. To će pokriti propuštene ciljeve automatski.",
    manual_lazy_title="Niste postigli svoj cilj danas.",
    manual_lazy_subtitle="Vaš cilj će se nastaviti, ako ste označili danas kao Dan ljenčarenja.",
    manual_lazy_title_used="Danas je Dan ljenčarenja.",
    manual_lazy_subtitle_used="Možete zaraditi više Dana ljenčarenja obaranjem osobnih rekorda.",
    manual_fail_ytd_title = "Završili ste svoj niz jučer.",
    manual_fail_ytd_subtitle = "Postignuti niz je %d dugačak.",

    active_time_format_0="%dm",
    active_time_format_1="%ds",
    active_time_format_2="%ds %dm",
    activie_run_format_0="Trčali ste %s. Jako dobro!",
    activie_run_format_1="Trčali ste %s, Odlično!",
    activie_run_format_2="Trčali ste %s.",
    activie_run_consumed="Potrošeno %dcal. %s",

    get_distance_format="oko %dm.",
    get_distance_format_british="%d inches",
    activity_walk_format="%s Prohodano %d koraka %s",
    activity_walk_consumed_format="Potrošeno %dkal %s.",
    activity_rope_skipping_format="%s preskakanje užeta %d puta",
    activity_situp_format="%s %d trbušnjaka",
    activity_consumed_format="Potrošeno %dcal %s",
    activity_activity_format="%s Vježbano %s %s",
    activity_activity_format_run="%s Vježbano %s, trčano %s",
    last_night_sleeped_good_format="Prošle noći spavali ste %s.",
    last_night_sleeped_normal_format="Prošle noći spavali ste %s.",
    deep_sleep_format="Faza dubokog sna je bila %.",

    battery_low_info="Stavite Mi Band na punjenje.",
    battery_very_low_info="Baterija Mi Banda je skoro prazna.",

    cannot_find_bracelet="Ne možete pronaći svoj Mi Band?",
    cannot_find_bracelet_info="Uvjerite se da je baterija vašeg Mi Banda napunjena.",

    bracelet_disconnect = "Ne mogžete se povezati? Kliknite za pomoć.",

    challenge_to_get="%s dana od postizanja novog rekorda!",
    record_reach_max="Izjednačili ste svoj postojeći rekord!",
    new_record_born="Postigli ste novi rekord!",

	   ------====== Weather tips ===============
    weather_tips_title_0 = "Teško zagađenje, pokušajte ostati u zatvorenom prostoru",
    weather_tips_title_1 = "Teško zagađenje, pokušajte ostati u zatvorenom prostoru",
    weather_tips_info = "Trbušnjaci ili preskakanje užeta su odlične vježbe u zatvorenom!",

    ---------------Weight scale -------------------
    welcome_use_weight_scale = "Dobrodošli u korištenje vage!",
    welcome_use_weight_scale_info = "Naučite više o vagi",
    welcome_use_weight_scale_not_bind = "Dodirnite da povežete vage",
    welcome_use_mi_health="Dobrodošli u korištenje Mi Banda",

    select_devices="Odaberite uređaje za uparivanje",
    daily_steps_not_comlete = "%s preostalo koraka"
    am_format="%sAM",
    pm_format="%sPM",
 }
