-------------------------
-- Simplified Chinese Localization String resources
-- Huami Co, ltd. (2014)
-- Herbert dai
-- 20140731
-------------------------
localization_Chinese_table = {
    calories_table={
        {str="≈ Огурец грунт. (100г)",	calories=14},
		{str="≈ Бульон куриный (100г)",	calories=15},
		{str="≈ Капуста пекинская (100г)",	calories=16},
		{str="≈ Томаты соленые (100г)",	calories=19},
		{str="≈ Квас (100г)",	calories=20},
		{str="≈ Шампиньоны (100г)",	calories=20},
		{str="≈ Редис (100г)",	calories=21},
		{str="≈ Баклажаны (100г)",	calories=24},
		{str="≈ Тыква (100г)",	calories=25},
		{str="≈ Квашеная капуста (100г)",	calories=25},
		{str="≈ Айран (100г)",	calories=26},
		{str="≈ Грибной суп (100г)",	calories=26},
		{str="≈ Брокколи (100г)",	calories=27},
		{str="≈ Овощной суп (100г)",	calories=28},
		{str="≈ Клубника (100г)",	calories=30},
		{str="≈ Щи (100г)",	calories=31},
		{str="≈ Борщ (100г)",	calories=36},
		{str="≈ Суп мисо (100г)",	calories=36},
		{str="≈ Свекольник (100г)",	calories=36},
		{str="≈ Яблоко (100г)",	calories=37},
		{str="≈ Апельсин (100г)",	calories=38},
		{str="≈ Картофельный суп (100г)",	calories=39},
		{str="≈ Арбуз (100г)",	calories=39},
		{str="≈ Суп щавелевый (100г)",	calories=40},
		{str="≈ Простокваша 1% (100г)",	calories=40},
		{str="≈ Рассольник (100г)",	calories=42},
		{str="≈ Кока-Кола (100г)",	calories=42},
		{str="≈ Молоко 1.5% (100г)",	calories=45},
		{str="≈ Red Bull (100г)",	calories=45},
		{str="≈ Уха (100г)",	calories=46},
		{str="≈ Персик (100г)",	calories=46},
		{str="≈ Сыр Хохланд (25г)",	calories=48},
		{str="≈ Вишня (100г)",	calories=52},
		{str="≈ Апельсиновый сок (100г)",	calories=54},
		{str="≈ Кефир 3.2% (100г)",	calories=56},
		{str="≈ Окрошка (100г)",	calories=57},
		{str="≈ Молоко 3.2% (100г)",	calories=58},
		{str="≈ Аджика (100г)",	calories=59},
		{str="≈ Рататуй (100г)",	calories=60},
		{str="≈ Пюре с мол. (100г)",	calories=65},
		{str="≈ Гороховый суп (100г)",	calories=66},
		{str="≈ Манго (100г)",	calories=67},
		{str="≈ Овсяная каша (100г)",	calories=68},
		{str="≈ Суп из чечевицы (100г)",	calories=68},
		{str="≈ Клубничное желе (100г)",	calories=69},
		{str="≈ Солянка сборная (100г)",	calories=69},
		{str="≈ Йогурт 1.5% слад. (100г)",	calories=70},
		{str="≈ Крабовые палочки (100г)",	calories=73},
		{str="≈ Суп харчо (100г)",	calories=75},
		{str="≈ Кальмары (100г)",	calories=75},
		{str="≈ Шампанское (100г)",	calories=76},
		{str="≈ Вино 13% (100г)",	calories=78},
		{str="≈ Вареники с капустой (100г)",	calories=79},
		{str="≈ Гуляш с капустой (100г)",	calories=81},
		{str="≈ Картофель отварной (100г)",	calories=82},
		{str="≈ Абсент 60% (100г)",	calories=83},
		{str="≈ Пюре с мол.и масл. (100г)",	calories=85},
		{str="≈ Яйцо вареное (55г)",	calories=88},
		{str="≈ Банан (100г)",	calories=89},
		{str="≈ Кабачковая икра (100г)",	calories=90},
		{str="≈ Фасоль в томате (100г)",	calories=92},
		{str="≈ Кетчуп (100г)",	calories=93},
		{str="≈ Рис с овощами (100г)",	calories=94},
		{str="≈ Зерновой тост (1шт)",	calories=95},
		{str="≈ Тунец (100г)",	calories=96},
		{str="≈ Судак отварной (100г)",	calories=97},
		{str="≈ Манная каша мол. (100г)",	calories=98},
		{str="≈ Овощное рагу (100г)",	calories=99},
		{str="≈ Карп отварной (100г)",	calories=102},
		{str="≈ Фруктовый салат (100г)",	calories=103},
		{str="≈ Филе индейки (100г)",	calories=104},
		{str="≈ Свинной балык (100г)",	calories=105},
		{str="≈ Плов с курицей (100г)",	calories=106},
		{str="≈ Рис (100г)",	calories=113},
		{str="≈ Цеппелины (100г)",	calories=117},
		{str="≈ Яичница",	calories=119},
		{str="≈ Икра кабачковая (100г)",	calories=122},
		{str="≈ Майонез японский (100г)",	calories=134},
		{str="≈ Зефир (1шт)",	calories=135},
		{str="≈ Творог (100г)",	calories=136},
		{str="≈ Авокадо ролл",	calories=140},
		{str="≈ Капучино (100г)",	calories=140},
		{str="≈ Лобио (100г)",	calories=141},
		{str="≈ Говядина, язык (100г)",	calories=146},
		{str="≈ Говяжий гуляш (100г)",	calories=148},
		{str="≈ Куриное филе вар. (100г)",	calories=153},
		{str="≈ Картошка жар. (100г)",	calories=154},
		{str="≈ Пицца маргарита (100г)",	calories=157},
		{str="≈ Тефтели (100г)",	calories=159},
		{str="≈ Гречневая каша (100г)",	calories=160},
		{str="≈ Сырок Чудо (40г)",	calories=164},
		{str="≈ Хлеб ржаной (100г)",	calories=165},
		{str="≈ Индейка жареная (100г)",	calories=165},
		{str="≈ Салат мимоза (100г)",	calories=183},
		{str="≈ Долма (100г)",	calories=183},
		{str="≈ Копченая курица (100г)",	calories=184},
		{str="≈ Салат Оливье (100г)",	calories=187},
		{str="≈ Зразы картофельные (100г)",	calories=190},
		{str="≈ Биток свиной (100г)",	calories=195},
		{str="≈ Сардельки (100г)",	calories=198},
		{str="≈ Лосось (201г)",	calories=201},
		{str="≈ Сметана 20% (100г)",	calories=204},
		{str="≈ Сливки (100г)",	calories=206},
		{str="≈ Паста болонез (100г)",	calories=208},
		{str="≈ Азу (100г)",	calories=214},
		{str="≈ Хлеб черный (100г)",	calories=214},
		{str="≈ Цукаты (100г)",	calories=216},
		{str="≈ Салат столичный (100г)",	calories=217},
		{str="≈ Сельдь соленая (100г)",	calories=217},
		{str="≈ Жульен грибной (100г)",	calories=219},
		{str="≈ Салат цезарь (100г)",	calories=221},
		{str="≈ Омлет (100г)",	calories=222},
		{str="≈ Светлое пиво (0,5л)",	calories=225},
		{str="≈ Хлеб овсяный (100г)",	calories=226},
		{str="≈ Рагу из баранины (100г)",	calories=226},
		{str="≈ Пломбир (100г)",	calories=227},
		{str="≈ Гамбургер",	calories=229},
		{str="≈ Жаркое из свинины (100г)",	calories=233},
		{str="≈ Батон (100г)",	calories=235},
		{str="≈ Лаваш (100г)",	calories=236},
		{str="≈ Водка 40% (100г)",	calories=237},
		{str="≈ Бастурма (100г)",	calories=240},
		{str="≈ Хамон (100г)",	calories=241},
		{str="≈ Хлеб пшеничный (100г)",	calories=242},
		{str="≈ Сосиски русские (100г)",	calories=243},
		{str="≈ Равиоли (100г)",	calories=245},
		{str="≈ Красная икра (100г)",	calories=249},
		{str="≈ Шаурма (100г)",	calories=250},
		{str="≈ Колбаса вареная (100г)",	calories=257},
		{str="≈ Сосиски куриные (100г)",	calories=259},
		{str="≈ Котлеты (100г)",	calories=260},
		{str="≈ Изюм (100г)",	calories=262},
		{str="≈ Чизбургер",	calories=264},
		{str="≈ Сосиски мол. (100г)",	calories=270},
		{str="≈ Ветчина (100г)",	calories=270},
		{str="≈ Мойва копченая (100г)",	calories=270},
		{str="≈ МакНаггетс (100г)",	calories=272},
		{str="≈ Кровянка (100г)",	calories=274},
		{str="≈ Мясо в шубе (100г)",	calories=274},
		{str="≈ Пельмени (100г)",	calories=275},
		{str="≈ Плов со свининой (100г)",	calories=281},
		{str="≈ Лосось гриль (100г)",	calories=283},
		{str="≈ Сырок Дружба (100г)",	calories=287},
		{str="≈ Черная икра (100г)",	calories=289},
		{str="≈ Майонез (100г)",	calories=299},
		{str="≈ Цветочный мед (100г)",	calories=302},
		{str="≈ Картофель фри (100г)",	calories=303},
		{str="≈ Салат Оливье (100г)",	calories=305},
		{str="≈ Скумбрия соленая (100г)",	calories=305},
		{str="≈ Финики (100г)",	calories=306},
		{str="≈ Оладьи с яблоками (100г)",	calories=306},
		{str="≈ Голубцы (100г)",	calories=311},
		{str="≈ Беляш (100г)",	calories=320},
		{str="≈ Оладьи (100г)",	calories=322},
		{str="≈ Омлет с сыром (100г)",	calories=324},
		{str="≈ Колбаса ливерная (100г)",	calories=326},
		{str="≈ Колбаски охотничьи (100г)",	calories=326},
		{str="≈ Пончики (100г)",	calories=329},
		{str="≈ Ватрушка (100г)",	calories=331},
		{str="≈ Блины с маслом (100г)",	calories=332},
		{str="≈ Люля-кебаб (100г)",	calories=339},
		{str="≈ Сушки (100г)",	calories=341},
		{str="≈ Макароны Макфа (100г)",	calories=344},
		{str="≈ Спагетти (100г)",	calories=344},
		{str="≈ Кекс (100г)",	calories=345},
		{str="≈ Пряник (100г)",	calories=350},
		{str="≈ Бефстроганов (100г)",	calories=355},
		{str="≈ Российский сыр (100г)",	calories=360},
		{str="≈ Кукурузные хлопья (100г)",	calories=363},
		{str="≈ Макароны (100г)",	calories=371},
		{str="≈ Бифштекс (100г)",	calories=384},
		{str="≈ Сухари (100г)",	calories=386},
		{str="≈ Сахар-песок  (100г)",	calories=398},
		{str="≈ Козинаки (100г)",	calories=419},
		{str="≈ Овсяное печенье (100г)",	calories=440},
		{str="≈ Лапша Роллтон  (100г)",	calories=448},
		{str="≈ Торт муравейник (100г)",	calories=452},
		{str="≈ Шницель (100г)",	calories=456},
		{str="≈ Лазанья (100г)",	calories=460},
		{str="≈ Фуа-гра (100г)",	calories=462},
		{str="≈ Торт Медовик  (100г)",	calories=478},
		{str="≈ Попкорн (100г)",	calories=480},
		{str="≈ Твикс",	calories=483},
		{str="≈ Сникерс",	calories=497},
		{str="≈ Бекон (100г)",	calories=500},
		{str="≈ Биг Мак",	calories=510},
		{str="≈ Чипсы Lays Max (100г)",	calories=510},
		{str="≈ Халва (100г)",	calories=522},
		{str="≈ Шоколад KitKat",	calories=524},
		{str="≈ Роял Чизбургер (100г)",	calories=530},
		{str="≈ Тирамису (100г)",	calories=540},
		{str="≈ Чипсы Pringles (100г)",	calories=540},
		{str="≈ Шоколад (100г)",	calories=546},
		{str="≈ Торт Наполеон (100г)",	calories=552},
		{str="≈ Салями (100г)",	calories=568},
		{str="≈ Гусь жареный (100г)",	calories=620},
		{str="≈ Майонез Евр. (100г)",	calories=665},
		{str="≈ Пельмени жареные (100г)",	calories=764},
		{str="≈ Сало (100г)",	calories=797},
		{str="≈ Биг Тейсти",	calories=850},
    },

    ok='OK',

    hour='ч.',
    minute='мин.',
    month='мес.',
    day='дн.',
    step="ш.",
    km='км',
	mile='миль',
    minute_format='%d мин.',
    hour_minute_format='%d ч. %d мин.',
    hour_format='%d ч.',

    welcome_use="Добро пожаловать",
    last_week_walked_format='За последнюю неделю Вы прошли шагов: %d',
    last_week_walked_info_format='Пройдено %d км, сожжено %d ккал.',
    last_month_walked_format='За последний месяц Вы прошли шагов: %d',
    last_month_walked_info_format='Пройдено %d км, сожжено %d ккал.',

    get_over_format=", около %d гр. жира",
    click_to_get_help="Инструкция по эксплуатации",
    take_a_walk="Прогуляйтесь с браслетом",
    take_a_walk_info="Браслет будет отслеживать Вашу активность в течение дня",
    unlock_hint="Разблокировка устройства",
    unlock_hint_info="Используйте браслет для автоматической разблокировки устройства",
	unlock_password_hint="Разблокировка устройства браслетом",
    unlock_password_hint_info="Установите разблокировку устройства браслетом для избежания потери устройства",
    no_data_hint_0="Национальный фонд сна США рекомендует спать 7-9 часов в сутки.",
    no_data_hint_1="Повторение - мать учения.",
    no_data_hint_2="Стремитесь к прогрессу а не к идеалу.",
    no_data_hint_3="Нормальный взрослый человек спит 15%-20% от общего времени сна в глубокой фазе сна.",
    not_binded_hint="Браслет не подключен к этому аккаунту",
	not_binded_hint_info="Вы также можете выбрать весы в меню",
    new_record_info="Новый рекорд!",
    new_record_format="%d шаг., %s %d",
    today_goal_reached="Сегодня Вы достигли свою цель!",
	today_goal_reached_click_info="Нажмите, чтобы посмотреть",
    week_continue_reach_goal="Вы",
	
	-- Continue reach goals string
    challenge_format="Вы достигаете цели %d дн. подряд!",
    personal_best_format="Лучший рекорд %d дн.!",
	continue_with_skips_title="Вы не достигли цели вчера. Назовем его ленивым днем ;)",
	continue_with_skips_title_today="Вы не достигли цели сегодня. Назовем этот день ленивым ;)",
    personal_best_with_skips_format="У Вас осталось дней отдыха: %d ;)",
    continue_used_n_skips_format="Вы достигаете свою цель %d дней! У Вас есть %d ленивых дней ;)",
    continue_used_0_skips_format="Вы достигаете свою цель %d дней! У Вас не осталось дней отдыха.",
    personal_best_on_skip_day_title="%d дн. подряд! Вы заработали день отдыха!",
    personal_best_on_skip_day_info="За каждое достижение цели семь дней подряд, Вы получатете один день отдыха. Он будет автоматически использован при недостижении цели.",
	manual_lazy_title="Вы не достигли сегодня своей цели.",
    manual_lazy_subtitle="Достижение будет продолжено, если Вы отметите сегодняшний день как день отдыха.",
    manual_lazy_title_used="Сегодня день отдыха",
    manual_lazy_subtitle_used="Вы можете получить больше дней отдыха улучшая свои личные рекорды.",
    manual_fail_ytd_title = "Продолжительность достижений прервана вчера.",
    manual_fail_ytd_subtitle = "Продолжительность достижений %d",
	
    active_time_format_0="%d мин.",
    active_time_format_1="%d ч.",
    active_time_format_2="%d ч. %d мин.",
    activie_run_format_0="Пробежали %s. Отличная работа!",
    activie_run_format_1="Пробежали %s. Это фантастика!",
    activie_run_format_2="Пробежали %s.",
    activie_run_consumed="Сожжено %d ккал. %s",

    get_distance_format=", всего %d м.",
	get_distance_format_british="%d фут",
    activity_walk_format="%s пройдено %d шаг., %s",
    activity_walk_consumed_format="Сожжено %d ккал. %s",
	activity_rope_skipping_format="%s прыжков на скакалке %d",
    activity_situp_format="%s сделал(а) %d упраж. для пресса",
    activity_consumed_format="Сожжено %d ккал. %s",
    activity_activity_format="%s %s тренировки %s",
	activity_activity_format_run="%s %s тренировки, пробежали %s",
    last_night_sleeped_good_format="Прошлой ночью Вы спали %s",
    last_night_sleeped_normal_format="Прошлой ночью Вы спали %s",
    deep_sleep_format="Глубокий сон %s",

    battery_low_info="Зарядите браслет",
    battery_very_low_info="Батарея браслета разряжена",

    cannot_find_bracelet="Не удается найти браслет",
    cannot_find_bracelet_info="Убедитесь что браслет заряжен и находится рядом с устройством",
	
	bracelet_disconnect = "Не удается подключиться? Нажмите, чтобы получить помощь.",
	
    challenge_to_get="%s дн. с момента нового рекорда!",
    record_reach_max="Вы побили свой рекорд!",
    new_record_born="Новый рекорд!",
	
	---====== Weather tips ===============
	weather_tips_title_0 = "Высокий уровень загрязнения. Постарайтесь оставаться дома.",
    weather_tips_title_1 = "Высокий уровень загрязнения. Постарайтесь оставаться дома.",
    weather_tips_info = "Упражнения для пресса, прыжки на скакалке и отжимания - отличный способ держать себя в форме не выходя из дома!",
	
	---------------Weight scale -------------------
    welcome_use_weight_scale = "Привет!",
    welcome_use_weight_scale_not_bind = "Нажмите для добавления весов",
    welcome_use_mi_health="Привет!",
	
	select_devices="Выберите устройство для сопряжения",
	daily_steps_not_comlete = "Осталось шагов: %s"
	
	am_format="%sAM",
    pm_format="%sPM",
}
